# reman shell integration for nushell (generated by `reman init nu`). Nushell loads it on start
# from its autoload folder:
#   mkdir ($nu.data-dir | path join "vendor/autoload")
#   reman init nu | save -f ($nu.data-dir | path join "vendor/autoload/reman.nu")
# Successes are appended to reman's spool file (no process at all; the daemon drains it every
# second). A failure runs the slim reman-hook and waits briefly for the fix suggestion.
#   Up = finder (this folder)   Ctrl-R = finder (all folders)   Alt-F = insert suggested fix
#   Alt-N on an empty line = what you usually run next here (again: the next idea); nushell
#   repaints its prompt over anything a key binding prints, so the line comes without its reason
const __reman_exe = "__REMAN__"
const __reman_hook = "__HOOK__"
const __reman_spool = "__SPOOL__"

def --wrapped reman [...args] { ^$__reman_exe ...$args }

# rcd <words>: go to the folder where you ran what the words describe (or whose path has them).
# `rcd alembic 2` takes the second match; `rcd` lists where you were lately, `rcd 3` goes there.
def --env rcd [...words: string] {
  let p = (do -i { ^$__reman_exe goto ...$words } | default "" | str trim)
  if ($p | is-not-empty) and ($p | lines | length) == 1 and ($p | path exists) { cd $p } else if ($p | is-not-empty) { print $p }
}

# one session per shell
$env.REMAN_SESSION = $"nu-(random uuid)"
$env.__REMAN_CMD = ""
$env.__REMAN_FIX = ""

def --env __reman_preexec [] {
  $env.__REMAN_CMD = (commandline)
  # inside `reman shell`, what the command prints is kept: it starts here (the prompt ends it)
  if ($env.REMAN_PTY? | is-not-empty) and ($env.__REMAN_CMD | str trim | is-not-empty) and not ($env.__REMAN_CMD | str starts-with "__reman_") {
    $env.__REMAN_CAP = $"($env.REMAN_SESSION)-(date now | format date '%s%f')"
    __reman_beat
    print -n $"(ansi escape)]46031711;C;($env.__REMAN_CAP)(char bel)"
  }
}

# (on Windows the terminal reman shell runs is ConPTY, which draws text on its own beat but
# passes a mark on at once: a mark waits one beat, so it lands after what came before it)
def __reman_beat [] {
  if $nu.os-info.name == "windows" { sleep 30ms }
}

def --env __reman_precmd [] {
  let cmd = ($env.__REMAN_CMD? | default "")
  $env.__REMAN_CMD = ""
  let cap = ($env.__REMAN_CAP? | default "")
  $env.__REMAN_CAP = ""
  if ($cap | is-not-empty) {
    __reman_beat
    print -n $"(ansi escape)]46031711;D;($cap)(char bel)"
  }
  # a leading space: never recorded; nor reman's own keys (nushell runs this hook for them too)
  if ($cmd | str trim | is-empty) or ($cmd | str starts-with " ") or ($cmd | str starts-with "__reman_") { return }
  let ec = ($env.LAST_EXIT_CODE? | default 0)
  let ms = ($env.CMD_DURATION_MS? | default "0" | into int)
  # a fix is offered for the command just run, until the next one
  $env.__REMAN_FIX = ""
  if $ec != 0 {
    $env.__REMAN_FIX = (with-env {REMAN_CAPTURE: $cap} { do -i { ^$__reman_hook record --exit $ec --cwd $env.PWD --duration-ms $ms --suggest --print-fix -- $cmd } } | default "" | str trim)
  } else {
    let run = {op: "ingest", command: $cmd, exit: 0, cwd: $env.PWD, session: $env.REMAN_SESSION, actor: "human", duration_ms: $ms}
    let line = (if ($cap | is-empty) { $run } else { $run | insert capture $cap } | to json -r)
    $"($line)\n" | save --append $__reman_spool
  }
}

# "last time here": asked when the folder changes (the daemon answers once per session and folder)
def __reman_welcome [dir: string] {
  do -i { ^$__reman_hook welcome --cwd $dir --session $env.REMAN_SESSION }
}

def --env __reman_find [scope: string] {
  let line = (commandline)
  let picked = (with-env {REMAN_FIND_QUERY: $line} { do -i { ^$__reman_exe find --scope $scope --cwd $env.PWD } } | default "" | str trim --right)
  if ($picked | is-empty) { return }
  # a command with a blank: char 1 marks where the cursor goes
  let mark = (char -i 1)
  let at = ($picked | str index-of --grapheme-clusters $mark)
  commandline edit --replace ($picked | str replace $mark "")
  if $at >= 0 { commandline set-cursor $at }
}

def --env __reman_insert_fix [] {
  if ($env.__REMAN_FIX? | default "" | is-not-empty) {
    commandline edit --replace $env.__REMAN_FIX
    return
  }
  # no fix waiting: what Alt-F does without reman, the end of the next word
  let text = (commandline | split chars)
  mut i = (commandline get-cursor)
  let n = ($text | length)
  while $i < $n and ($text | get $i) == " " { $i = $i + 1 }
  while $i < $n and ($text | get $i) != " " { $i = $i + 1 }
  commandline set-cursor $i
}

# Alt-N on an empty line: what you'd run next here, ready to edit (Alt-N again: the next idea, up
# to 3)
def --env __reman_nextup [] {
  let line = (commandline)
  mut i = 0
  if ($line | str trim | is-not-empty) {
    if ($env.__REMAN_NEXT? | default "") != $line { return }
    $i = (($env.__REMAN_NEXT_I? | default 0 | into int) + 1)
  }
  let index = $i
  let out = (do -i { ^$__reman_hook nextup --cwd $env.PWD --session $env.REMAN_SESSION --index $index } | default "" | lines | get 0? | default "")
  if ($out | is-empty) { return }
  let parts = ($out | split row (char tab))
  $env.__REMAN_NEXT = ($parts | get 0)
  $env.__REMAN_NEXT_I = ($parts | get 2? | default 0 | into int)
  commandline edit --replace ($parts | get 0)
}

$env.config = ($env.config? | default {})
$env.config.hooks = ($env.config.hooks? | default {})
$env.config.hooks.pre_execution = ($env.config.hooks.pre_execution? | default [] | append {|| __reman_preexec })
$env.config.hooks.pre_prompt = ($env.config.hooks.pre_prompt? | default [] | append {|| __reman_precmd })
$env.config.hooks.env_change = ($env.config.hooks.env_change? | default {})
$env.config.hooks.env_change.PWD = ($env.config.hooks.env_change.PWD? | default [] | append {|before, after| __reman_welcome $after })
$env.config.keybindings = ($env.config.keybindings? | default [] | append [
  {name: reman_find_all, modifier: control, keycode: char_r, mode: [emacs, vi_insert, vi_normal], event: {send: executehostcommand, cmd: "__reman_find all"}}
  # a menu that's open keeps Up
  {name: reman_find_here, modifier: none, keycode: up, mode: [emacs, vi_insert], event: {until: [{send: menuup}, {send: executehostcommand, cmd: "__reman_find folder"}]}}
  {name: reman_fix, modifier: alt, keycode: char_f, mode: [emacs, vi_insert], event: {send: executehostcommand, cmd: "__reman_insert_fix"}}
  {name: reman_next, modifier: alt, keycode: char_n, mode: [emacs, vi_insert], event: {send: executehostcommand, cmd: "__reman_nextup"}}
])
__reman_welcome $env.PWD
