# reman shell integration for xonsh (generated by `reman init xonsh`). In ~/.xonshrc:
#   execx($(reman init xonsh))
# Successes are appended to reman's spool file (no process at all; the daemon drains it every
# second). A failure runs the slim reman-hook and waits briefly for the fix suggestion.
#   Up = finder (this folder)   Ctrl-R = finder (all folders)   Alt-F = insert suggested fix
#   Alt-N on an empty line = what you usually run next here (again: the next idea)
import json as _reman_json
import os as _reman_os
import random as _reman_random
import subprocess as _reman_sp

_REMAN_EXE = "__REMAN__"
_REMAN_HOOK = "__HOOK__"
_REMAN_SPOOL = "__SPOOL__"
# the fix offered for the command just run (until the next one), and Alt-N's last idea
_reman_state = {"fix": "", "next": "", "next_i": 0}

aliases["reman"] = [_REMAN_EXE]

# one session per shell
__xonsh__.env["REMAN_SESSION"] = f"xonsh-{_reman_os.getpid()}-{_reman_random.randrange(1 << 30)}"


def _reman_env(**extra):
    env = __xonsh__.env.detype()
    env.update(extra)
    return env


def _reman_out(args, **extra):
    """What a reman command printed, or "" (it never stops the shell)."""
    try:
        p = _reman_sp.run(args, stdout=_reman_sp.PIPE, env=_reman_env(**extra), encoding="utf-8", errors="replace")
        return p.stdout or ""
    except OSError:
        return ""


def _reman_rcd(args):
    """rcd <words>: go to the folder where you ran what the words describe (or whose path has
    them). `rcd alembic 2` takes the second match; `rcd` lists where you were lately."""
    p = _reman_out([_REMAN_EXE, "goto", *args]).strip()
    if p and "\n" not in p and _reman_os.path.isdir(p):
        from xonsh.dirstack import cd
        cd([p])
    elif p:
        print(p)


aliases["rcd"] = _reman_rcd


def _reman_mark(kind, cap):
    """Inside `reman shell`: where what a command prints starts (C) and ends (D). On Windows that
    terminal is ConPTY, which draws text on its own beat but passes a mark on at once: a mark
    waits one beat, so it lands after what came before it."""
    if _reman_os.name == "nt":
        import time
        time.sleep(0.03)
    try:
        with open("CONOUT$" if _reman_os.name == "nt" else "/dev/tty", "w") as tty:
            tty.write(f"\x1b]46031711;{kind};{cap}\x07")
    except OSError:
        pass


@events.on_precommand
def _reman_precommand(cmd="", **kw):
    if __xonsh__.env.get("REMAN_PTY") and (cmd or "").strip():
        _reman_state["cap"] = f"{__xonsh__.env['REMAN_SESSION']}-{_reman_random.randrange(1 << 40)}"
        _reman_mark("C", _reman_state["cap"])


@events.on_postcommand
def _reman_postcommand(cmd="", rtn=0, out=None, ts=None, **kw):
    cap = _reman_state.pop("cap", "")
    if cap:
        _reman_mark("D", cap)
    cmd = (cmd or "").rstrip("\n")
    # a leading space: never recorded
    if not cmd.strip() or cmd.startswith(" "):
        return
    ms = int((ts[1] - ts[0]) * 1000) if ts and len(ts) == 2 and ts[1] else 0
    cwd = _reman_os.getcwd()
    _reman_state["fix"] = ""
    if rtn:
        _reman_state["fix"] = _reman_out([_REMAN_HOOK, "record", "--exit", str(rtn), "--cwd", cwd, "--duration-ms", str(ms), "--suggest", "--print-fix", "--", cmd], REMAN_CAPTURE=cap).strip()
    else:
        line = {"op": "ingest", "command": cmd, "exit": 0, "cwd": cwd, "session": __xonsh__.env["REMAN_SESSION"], "actor": "human", "duration_ms": ms}
        if cap:
            line["capture"] = cap
        try:
            with open(_REMAN_SPOOL, "a", encoding="utf-8") as f:
                f.write(_reman_json.dumps(line) + "\n")
        except OSError:
            pass


# "last time here": asked when the folder changes (the daemon answers once per session and folder)
@events.on_chdir
def _reman_chdir(olddir=None, newdir=None, **kw):
    try:
        _reman_sp.run([_REMAN_HOOK, "welcome", "--cwd", newdir or _reman_os.getcwd(), "--session", __xonsh__.env["REMAN_SESSION"]], env=_reman_env())
    except OSError:
        pass


_reman_chdir(newdir=_reman_os.getcwd())


@events.on_ptk_create
def _reman_keys(bindings, **kw):
    from prompt_toolkit.application import get_app, run_in_terminal
    from prompt_toolkit.filters import Condition
    from prompt_toolkit.key_binding.bindings.named_commands import get_by_name

    def find(event, scope):
        buf = event.current_buffer
        picked = _reman_out([_REMAN_EXE, "find", "--scope", scope, "--cwd", _reman_os.getcwd()], REMAN_FIND_QUERY=buf.text).rstrip("\r\n")
        # the finder put the cursor back on this prompt: draw it again from there
        event.app.renderer.erase()
        if picked:
            # a command with a blank: \x01 marks where the cursor goes
            at = picked.find("\x01")
            buf.text = picked.replace("\x01", "")
            buf.cursor_position = at if at >= 0 else len(buf.text)

    # a single line, no completion menu open: Up opens the finder (otherwise Up as usual)
    one_line = Condition(lambda: "\n" not in get_app().current_buffer.text and get_app().current_buffer.complete_state is None)

    def _all(event):
        find(event, "all")

    def _here(event):
        find(event, "folder")

    def _fix(event):
        if _reman_state["fix"]:
            event.current_buffer.text = _reman_state["fix"]
            event.current_buffer.cursor_position = len(_reman_state["fix"])
        else:
            # what Alt-F does without reman
            get_by_name("forward-word").call(event)

    # Alt-N on an empty line: what you'd run next here, ready to edit (Alt-N again: the next idea,
    # up to 3)
    def _next(event):
        buf = event.current_buffer
        i = 0
        if buf.text.strip():
            if buf.text != _reman_state["next"]:
                return
            i = _reman_state["next_i"] + 1
        out = _reman_out([_REMAN_HOOK, "nextup", "--cwd", _reman_os.getcwd(), "--session", __xonsh__.env["REMAN_SESSION"], "--index", str(i)])
        parts = (out.splitlines() or [""])[0].split("\t")
        if not parts[0]:
            return
        _reman_state["next"] = parts[0]
        _reman_state["next_i"] = int(parts[2]) if len(parts) > 2 and parts[2].isdigit() else i
        if i == 0 and len(parts) > 1:
            run_in_terminal(lambda: print(f"\x1b[90m  reman: {parts[1]}\x1b[0m"))
        buf.text = parts[0]
        buf.cursor_position = len(parts[0])

    # reman's keys (`reman settings`, Keys)
__KEYS__
