# reman shell integration (generated by `reman init powershell`). Replaces Atuin: captures every
# command with cwd + real exit code + duration + session, and binds the native finder.
#   UpArrow = finder scoped to this folder   Ctrl+R = finder over all folders   Alt+F = insert fix
#   Tab = normal completion; when there's nothing to complete, the finder
$global:__RemanExe = "__REMAN__"
# `reman` is the exe on PATH, not a wrapper function: PowerShell only gives native commands
# their argument completer (below)
$__remanDir = Split-Path -Parent $global:__RemanExe
if (($env:PATH -split ';') -notcontains $__remanDir) { $env:PATH = "$__remanDir;$env:PATH" }
Remove-Item Function:\reman -ErrorAction SilentlyContinue

# Tab completion for reman itself - the same engine as bash / zsh / fish (`reman complete`):
# subcommands and flags with their help, agents with their status, folders you could share,
# your own commands for forget / pin / check / fixes.
Register-ArgumentCompleter -Native -CommandName 'reman', 'reman.exe' -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $text = $commandAst.ToString()
  $upto = [Math]::Min([Math]::Max($cursorPosition - $commandAst.Extent.StartOffset, 0), $text.Length)
  $before = $text.Substring(0, $upto)
  $head = $before.Substring(0, $before.Length - [Math]::Min($wordToComplete.Length, $before.Length))
  $enc = [Console]::OutputEncoding
  try {
    [Console]::OutputEncoding = [Text.Encoding]::UTF8
    $lines = & $global:__RemanExe complete "--line=$head" "--cur=$wordToComplete" 2>$null
  } finally { [Console]::OutputEncoding = $enc }
  foreach ($l in @($lines)) {
    if (-not $l) { continue }
    $v, $d = $l -split "`t", 2
    $insert = if ($v -match "[\s'`"``$;&|(){}@#,]") { "'" + ($v -replace "'", "''") + "'" } else { $v }
    $type = if ($v.StartsWith('-')) { 'ParameterName' } else { 'ParameterValue' }
    [System.Management.Automation.CompletionResult]::new($insert, $v, $type, $(if ($d) { $d } else { $v }))
  }
}
# One session per shell. Never inherited: a window (or VS Code) started from this one is a
# different shell, and flows / "last command failed" are per shell.
if (-not $global:__RemanSessionId) { $global:__RemanSessionId = [guid]::NewGuid().ToString() }
$env:REMAN_SESSION = $global:__RemanSessionId

# One JSON line to the daemon. $waitMs > 0 waits (bounded) for the reply. If the daemon is down the
# run goes to the spool file (drained on next start) and the daemon is started in the background.
function global:__RemanSend {
  param($obj, [int]$waitMs = 0, [bool]$spool = $true)
  $json = ($obj | ConvertTo-Json -Compress)
  try {
    $c = New-Object Net.Sockets.TcpClient
    $iar = $c.BeginConnect('127.0.0.1', __PORT__, $null, $null)
    if (-not $iar.AsyncWaitHandle.WaitOne(250)) { $c.Close(); throw 'reman daemon down' }
    $c.EndConnect($iar)
    $st = $c.GetStream()
    $b = [Text.Encoding]::UTF8.GetBytes($json + "`n")
    $st.Write($b, 0, $b.Length); $st.Flush()
    $resp = $null
    if ($waitMs -gt 0) {
      $st.ReadTimeout = $waitMs
      try { $resp = (New-Object IO.StreamReader($st, [Text.Encoding]::UTF8)).ReadLine() | ConvertFrom-Json } catch { }
    }
    $c.Close()
    return $resp
  } catch {
    if (-not $spool) { return $null }
    try { [IO.File]::AppendAllText("__SPOOL__", $json + "`n", (New-Object Text.UTF8Encoding($false))) } catch { }
    $now = [DateTime]::UtcNow
    if (-not $global:__RemanSpawned -or ($now - $global:__RemanSpawned).TotalSeconds -gt 30) {
      $global:__RemanSpawned = $now
      try { Start-Process -FilePath $global:__RemanExe -ArgumentList 'daemon' -WindowStyle Hidden } catch { }
    }
    return $null
  }
}

# Warm the daemon when the shell starts (non-blocking), so the very first failure already gets a
# suggestion instead of landing in the spool.
try {
  $__c = New-Object Net.Sockets.TcpClient
  $__iar = $__c.BeginConnect('127.0.0.1', __PORT__, $null, $null)
  if (-not $__iar.AsyncWaitHandle.WaitOne(150)) {
    $global:__RemanSpawned = [DateTime]::UtcNow
    Start-Process -FilePath $global:__RemanExe -ArgumentList 'daemon' -WindowStyle Hidden
  }
  $__c.Close()
} catch { }

# ---- Capture ---------------------------------------------------------------------------------
# Whether a command failed is in `$?`, and only the FIRST statement of the prompt can read it -
# any statement before it resets it to True. So reman's prompt must run first. Tools that wrap
# the prompt after reman loads (a Python venv's Activate.ps1, conda, VS Code's shell integration)
# would run their own code first and turn every failure into a success. When one wraps us, we
# step back outside it and call it from there, handing it the real `$?`; when it unwinds (a
# venv's `deactivate` puts an older prompt back) we drop it again.
#   __RemanChain  wrappers installed after us, newest first
#   __RemanLevels the prompt object we installed at each chain depth (identity = "we're outermost")
#   __RemanDepth  $null outside a prompt; how deep the current prompt walk is

# Record the command that just finished (once: repeated prompts see the same history id).
# $trusted = we read `$?` first. Otherwise judge from what the command left behind.
function global:__RemanWelcome {
  # "last time here": asked when the folder changes; the daemon answers once per session and
  # folder, and only after a while away
  try {
    $here = (Get-Location).Path
    if ($here -eq $global:__RemanPwd) { return }
    $global:__RemanPwd = $here
    $r = __RemanSend @{ op = 'welcome'; cwd = $here; session = $env:REMAN_SESSION } 300 $false
    if ($r -and $r.line) { Write-Host "  reman: $($r.line)" -ForegroundColor DarkGray }
  } catch { }
}

function global:__RemanCapture {
  param([bool]$ok, $code, [bool]$trusted)
  try {
    $e0 = if ($global:Error.Count) { $global:Error[0] } else { $null }
    $h = Get-History -Count 1
    if ($h -and $h.Id -ne $global:__RemanLastHistId) {
      $global:__RemanLastHistId = $h.Id
      $newErr = $e0 -and -not [object]::ReferenceEquals($e0, $global:__RemanErr0)
      if (-not $trusted) {
        $ok = ($h.ExecutionStatus -eq 'Completed') -and -not $newErr -and -not ($code -and $code -ne $global:__RemanPrevCode)
      }
      $cmd = $h.CommandLine
      if ($cmd -and -not $cmd.StartsWith(' ') -and $cmd.Trim().Length -gt 1) {
        $exit = if ($ok) { 0 } elseif ($code) { $code } else { 1 }
        $dur = [int64]($h.EndExecutionTime - $h.StartExecutionTime).TotalMilliseconds
        $req = @{ op = 'ingest'; command = $cmd; exit = $exit; cwd = (Get-Location).Path;
                  session = $env:REMAN_SESSION; actor = 'human'; duration_ms = $dur }
        if ($exit -ne 0) {
          # what it printed, when PowerShell kept it (cmdlets; a native program's stderr isn't)
          if ($newErr) { try { $req.error = [string]$e0.Exception.Message } catch { } }
          $r = __RemanSend $req 400
          if ($r -and $r.suggest -and $r.suggest.command) {
            $global:__RemanFix = [string]$r.suggest.command
            $lead = switch ($r.suggest.kind) { 'proven' { 'last time this failed you ran' } 'same_error' { 'the same error was fixed by' } default { 'did you mean' } }
            Write-Host "  reman: $lead -> " -NoNewline -ForegroundColor DarkGray
            Write-Host $global:__RemanFix -NoNewline -ForegroundColor Cyan
            Write-Host '   (Alt+F inserts)' -ForegroundColor DarkGray
          }
          # it used to work here: what ran here since
          if ($r -and $r.note) { Write-Host "  reman: $($r.note)" -ForegroundColor DarkGray }
        } else { [void](__RemanSend $req 0) }
      }
    }
    $global:__RemanErr0 = $e0
    $global:__RemanPrevCode = $code
  } catch { }
}

function global:__RemanBasePrompt {
  if ($global:__RemanBase) { & $global:__RemanBase }
  else { "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) " }
}

# An updated reman reloads itself into open shells at the next prompt (one file-time check).
function global:__RemanAutoReload {
  try {
    $t = [IO.File]::GetLastWriteTimeUtc($global:__RemanExe)
    if ($global:__RemanExeTime -and $t -ne $global:__RemanExeTime) {
      $global:__RemanExeTime = $t
      . ([scriptblock]::Create((& $global:__RemanExe init powershell | Out-String)))
      Write-Host '  reman: updated - this shell now runs the new version' -ForegroundColor DarkGray
    }
  } catch { }
}

$global:__RemanPrompt = {
  # reman-prompt
  $ok = $global:?
  $code = $global:LASTEXITCODE
  if ($null -ne $global:__RemanDepth) {
    # a wrapper is calling the prompt it wrapped: go one level further in, `$?` intact
    $d = ++$global:__RemanDepth
    $global:LASTEXITCODE = $code
    if (-not $ok) { Write-Error 'reman: the last command failed' -ErrorAction Ignore }
    if ($d -lt @($global:__RemanChain).Count) { & @($global:__RemanChain)[$d] } else { __RemanBasePrompt }
    return
  }
  $cur = $function:global:prompt
  $levels = @($global:__RemanLevels)
  $k = -1
  for ($i = $levels.Count - 1; $i -ge 0; $i--) { if ([object]::ReferenceEquals($cur, $levels[$i])) { $k = $i; break } }
  $trusted = $k -ge 0
  if ($trusted -and $k -lt $levels.Count - 1) {
    # an older prompt of ours is back (a venv's `deactivate`): the wrappers added since are gone
    $global:__RemanChain = @(@($global:__RemanChain) | Select-Object -Skip ($levels.Count - 1 - $k))
    $global:__RemanLevels = @($levels | Select-Object -First ($k + 1))
  }
  __RemanCapture $ok $code $trusted
  __RemanWelcome
  if ($trusted) { __RemanAutoReload }
  $global:__RemanDepth = 0
  try {
    $global:LASTEXITCODE = $code
    if (-not $ok) { Write-Error 'reman: the last command failed' -ErrorAction Ignore }
    $p = if (@($global:__RemanChain).Count) { & @($global:__RemanChain)[0] } else { __RemanBasePrompt }
    if ($global:__RemanOsc) {
      # OSC 133: the last command ended (with its code), a prompt starts, input starts
      $esc = [char]27; $bel = [char]7
      $d = if ($ok) { 0 } elseif ($code) { $code } else { 1 }
      "$esc]133;D;$d$bel$esc]133;A$bel" + ($p -join '') + "$esc]133;B$bel"
    } else { $p }
  } finally {
    $global:__RemanDepth = $null
    if (-not $trusted) {
      # something wrapped the prompt after reman: step back outside it, keeping it inside
      $global:__RemanChain = @($cur) + @($global:__RemanChain)
      $function:global:prompt = [scriptblock]::Create($global:__RemanPrompt.ToString())
      $global:__RemanLevels = @($global:__RemanLevels) + @($function:global:prompt)
    }
  }
}

if ($null -eq $global:__RemanLevels) {
  # first load in this shell: the prompt that exists now is the one we build on
  $global:__RemanBase = $function:prompt
  $global:__RemanChain = @()
  $global:__RemanLevels = @()
  $global:__RemanLastHistId = -1
}
$global:__RemanDepth = $null
$function:global:prompt = [scriptblock]::Create($global:__RemanPrompt.ToString())
if ($global:__RemanLevels.Count) { $global:__RemanLevels[$global:__RemanLevels.Count - 1] = $function:global:prompt }
else { $global:__RemanLevels = @($function:global:prompt) }
$global:__RemanExeTime = try { [IO.File]::GetLastWriteTimeUtc($global:__RemanExe) } catch { $null }

# OSC 133 prompt marks, for terminals that show them (Windows Terminal, WezTerm): jump between
# commands, see each one's exit code. VS Code adds its own; REMAN_NO_OSC133 turns ours off.
$global:__RemanOsc = (-not $env:REMAN_NO_OSC133) -and ($env:TERM_PROGRAM -ne 'vscode') -and ($env:WT_SESSION -or $env:TERM_PROGRAM -eq 'WezTerm')

# PSReadLine reads each command line through PSConsoleHostReadLine. Wrapping it (as Atuin does)
# is a safety net for capture: if something replaced the prompt without calling reman's, the
# last command is still recorded here (__RemanCapture skips one it already has). It also marks
# where a command starts, for OSC 133.
if ((Get-Command PSConsoleHostReadLine -ErrorAction Ignore) -and -not $global:__RemanReadLine) {
  $global:__RemanReadLine = ${function:PSConsoleHostReadLine}
}
if ($global:__RemanReadLine) {
  function global:PSConsoleHostReadLine {
    try { __RemanCapture $true $global:LASTEXITCODE $false } catch { }
    $line = & $global:__RemanReadLine
    if ($global:__RemanOsc) { [Console]::Write("$([char]27)]133;C$([char]7)") }
    $line
  }
}

# Native finder. The query travels via env (Windows PowerShell 5.1 drops empty native args and
# mangles embedded quotes); the pick comes back through a temp file.
function global:__RemanFind {
  param([string]$line, [string]$scope)
  $tmp = [IO.Path]::GetTempFileName()
  $env:REMAN_FIND_QUERY = $line
  try {
    & $global:__RemanExe find --scope $scope --cwd ((Get-Location).Path) --result-file $tmp
    $chosen = [IO.File]::ReadAllText($tmp, [Text.Encoding]::UTF8)
  } catch { $chosen = $null }
  finally { Remove-Item Env:\REMAN_FIND_QUERY -ErrorAction SilentlyContinue; Remove-Item $tmp -ErrorAction SilentlyContinue }
  if ($chosen) { return $chosen.TrimEnd("`r", "`n") }
  return $null
}

if (Get-Module PSReadLine -ErrorAction SilentlyContinue) {
  Set-PSReadLineKeyHandler -Chord 'UpArrow' -BriefDescription 'reman history finder (this folder)' -ScriptBlock {
    $line = $null; $cur = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
    if ($line.Contains("`n")) { [Microsoft.PowerShell.PSConsoleReadLine]::PreviousLine(); return }
    $chosen = __RemanFind $line 'folder'
    if ($chosen) { [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $chosen) }
    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
  }
  Set-PSReadLineKeyHandler -Chord 'Ctrl+r' -BriefDescription 'reman history finder (all folders)' -ScriptBlock {
    $line = $null; $cur = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
    $chosen = __RemanFind $line 'all'
    if ($chosen) { [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $chosen) }
    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
  }
  # Tab: normal completion first; only when it changes nothing (empty line, or nothing matches)
  # does the finder open, seeded with what's typed. Shift+Tab keeps its default.
  Set-PSReadLineKeyHandler -Chord 'Tab' -BriefDescription 'complete, else reman finder' -ScriptBlock {
    param($key, $arg)
    $line = $null; $cur = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
    # `reman ...`: a menu of choices with their descriptions, never the finder
    if ($line -match '^\s*reman(\.exe)?(\s|$)') {
      [Microsoft.PowerShell.PSConsoleReadLine]::MenuComplete($key, $arg)
      return
    }
    if (-not [string]::IsNullOrWhiteSpace($line)) {
      [Microsoft.PowerShell.PSConsoleReadLine]::TabCompleteNext($key, $arg)
      $after = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$after, [ref]$cur)
      if ($after -ne $line) { return }
    }
    $chosen = __RemanFind $line 'folder'
    if ($chosen) { [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $chosen) }
    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
  }
  Set-PSReadLineKeyHandler -Chord 'Alt+f' -BriefDescription 'reman: insert suggested fix' -ScriptBlock {
    if ($global:__RemanFix) {
      $line = $null; $cur = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $global:__RemanFix)
    }
  }
}
