# reman shell integration for zsh (generated by `reman init zsh`).
# Captures cmd + cwd + exit + duration + session; Ctrl-R / Up open the native finder.
__reman_exe="__REMAN__"
reman() { "$__reman_exe" "$@" }
[[ -z "$REMAN_SESSION" ]] && export REMAN_SESSION="$(uuidgen 2>/dev/null || print -r -- $$-$RANDOM$RANDOM)"
zmodload zsh/datetime 2>/dev/null
autoload -Uz add-zsh-hook

__reman_preexec() {
  __reman_cmd="$1"
  __reman_start=$EPOCHREALTIME
}

__reman_precmd() {
  local ec=$?
  [[ -z "$__reman_cmd" ]] && return
  local cmd="$__reman_cmd"; __reman_cmd=
  local dur=$(( int((EPOCHREALTIME - __reman_start) * 1000) ))
  if (( ec != 0 )); then
    "$__reman_exe" record --exit $ec --cwd "$PWD" --duration-ms $dur --suggest -- "$cmd"
  else
    ( "$__reman_exe" record --exit $ec --cwd "$PWD" --duration-ms $dur -- "$cmd" & ) 2>/dev/null
  fi
}
add-zsh-hook preexec __reman_preexec
add-zsh-hook precmd __reman_precmd

__reman_find_widget() {
  local scope=$1 picked
  picked=$(REMAN_FIND_QUERY="$BUFFER" "$__reman_exe" find --scope "$scope" --cwd "$PWD" </dev/tty)
  if [[ -n "$picked" ]]; then
    BUFFER="$picked"
    CURSOR=${#BUFFER}
  fi
  zle reset-prompt
}
__reman_find_all() { __reman_find_widget all }
__reman_find_here() { __reman_find_widget folder }
zle -N __reman_find_all
zle -N __reman_find_here
bindkey '^R' __reman_find_all
bindkey '^[[A' __reman_find_here
bindkey '^[OA' __reman_find_here
