# reman shell integration for bash (generated by `reman init bash`).
# Capture is FORK-FREE: history is read via builtin redirection, JSON is built with parameter
# expansion, and the run goes straight to the daemon over bash's own /dev/tcp. Only when the
# daemon is down is the slim reman-hook spawned (it spools the run and starts the daemon).
#   Up = finder (this folder)   Ctrl-R = finder (all folders)   Alt-F = insert suggested fix
#   Alt-N on an empty line = what you usually run next here (again: the next idea)
#   Tab on an empty line = finder (Tab after text is normal completion)
__reman_exe="__REMAN__"
__reman_hook="__HOOK__"
__reman_port=__PORT__
# `reman settings` can open every shell inside `reman shell`, so what your commands print is kept
# too: this one hands over to a shell inside it, and closes when that one does (it goes on as
# usual when that can't start)
if [ __SHELL_LAYER__ = 1 ] && [ -z "$REMAN_PTY" ] && [[ $- == *i* ]] && [ -t 0 ] && [ "$TERM_PROGRAM" != vscode ]; then
  "$__reman_exe" shell -- "$BASH" -i
  __reman_s=$?
  [ $__reman_s -ne 97 ] && exit $__reman_s
fi
reman() { "$__reman_exe" "$@"; }
# rcd <words>: go to the folder where you ran what the words describe (or whose path has them).
# `rcd alembic 2` takes the second match; `rcd` lists where you were lately, `rcd 3` goes there.
rcd() {
  local p
  p=$("$__reman_exe" goto "$@") && [ -n "$p" ] || return
  command -v cygpath >/dev/null 2>&1 && p=$(cygpath -u "$p")
  cd -- "$p"
}
# one session per shell: the id lives in an unexported variable, so a child shell makes its own
[ -z "$__reman_sid" ] && __reman_sid="bash-$$-$RANDOM$RANDOM"
export REMAN_SESSION=$__reman_sid
__reman_histfile="${TMPDIR:-/tmp}/.reman-hist-$$"
# a command typed with a leading space is never recorded
case ":$HISTCONTROL:" in *:ignorespace:*|*:ignoreboth:*) ;; *) HISTCONTROL="${HISTCONTROL:+$HISTCONTROL:}ignorespace" ;; esac

__reman_q() { # JSON-quote $1 into REPLY
  local s=$1
  s=${s//\\/\\\\}; s=${s//\"/\\\"}; s=${s//$'\n'/\\n}; s=${s//$'\r'/\\r}; s=${s//$'\t'/\\t}
  s=${s//[[:cntrl:]]/}
  REPLY="\"$s\""
}

__reman_ms() { local t=${EPOCHREALTIME/[.,]/}; REPLY=$(( 10#$t / 1000 )); }

__reman_preexec() {
  [ -n "$COMP_LINE" ] && return
  [ -n "$__reman_start" ] && return
  __reman_ms; __reman_start=$REPLY
  # inside `reman shell`, what the command prints is kept: it starts here (the prompt ends it)
  if [ -n "$REMAN_PTY" ] && [[ $BASH_COMMAND != __reman_precmd* ]]; then
    __reman_cap="$REMAN_SESSION-$REPLY"
    __reman_beat
    printf '\e]46031711;C;%s\a' "$__reman_cap" >/dev/tty 2>/dev/null
  fi
}

# (on Windows the terminal reman shell runs is ConPTY, which draws text on its own beat but
# passes a mark on at once: a mark waits one beat, so it lands after what came before it)
__reman_beat() { case $OSTYPE in msys*|cygwin*) sleep 0.03 ;; esac; }

__reman_note() { # print JSON string field $2 of reply $1 as a dim reman line
  [[ $1 =~ \"$2\":\"(([^\"\\]|\\.)*)\" ]] || return
  local s=${BASH_REMATCH[1]}; s=${s//\\\"/\"}; s=${s//\\\\/\\}
  printf '\e[90m  reman: %s\e[0m\n' "$s" >&2
}

__reman_welcome() { # "last time here": asked when the folder changes (the daemon answers once)
  [[ $PWD == "$__reman_pwd" ]] && return
  __reman_pwd=$PWD
  __reman_q "$PWD"; local qd=$REPLY
  __reman_q "$REMAN_SESSION"; local qs=$REPLY
  local fd= reply=
  { exec {fd}<>"/dev/tcp/127.0.0.1/$__reman_port"; } 2>/dev/null
  [ -n "$fd" ] || return
  printf '%s\n' "{\"op\":\"welcome\",\"cwd\":$qd,\"session\":$qs}" >&$fd
  IFS= read -r -t 0.3 -u $fd reply
  exec {fd}>&-
  __reman_note "$reply" line
}

__reman_precmd() {
  local ec=$? start=$__reman_start line num cmd cap=$__reman_cap
  __reman_cap=
  if [ -n "$cap" ]; then __reman_beat; printf '\e]46031711;D;%s\a' "$cap" >/dev/tty 2>/dev/null; fi
  __reman_welcome
  __reman_start=
  [ -z "$start" ] && return $ec
  builtin history 1 > "$__reman_histfile" 2>/dev/null || return $ec
  IFS= read -r -d '' line < "$__reman_histfile"
  [[ $line =~ ^[[:space:]]*([0-9]+)\*?[[:space:]]+(.*)$ ]] || return $ec
  num=${BASH_REMATCH[1]}; cmd=${BASH_REMATCH[2]}; cmd=${cmd%$'\n'}
  [ "$num" = "$__reman_last_num" ] && return $ec
  __reman_last_num=$num
  __reman_fix=   # a fix is offered for the command just run, until the next one
  [ -z "$cmd" ] && return $ec
  __reman_ms; local dur=$(( REPLY - start ))
  __reman_q "$cmd"; local qc=$REPLY
  __reman_q "$PWD"; local qd=$REPLY
  __reman_q "$REMAN_SESSION"; local qs=$REPLY
  local json="{\"op\":\"ingest\",\"command\":$qc,\"exit\":$ec,\"cwd\":$qd,\"session\":$qs,\"actor\":\"human\",\"duration_ms\":$dur,\"ts\":$EPOCHSECONDS${cap:+,\"capture\":\"$cap\"}}"
  local fd= reply=
  { exec {fd}<>"/dev/tcp/127.0.0.1/$__reman_port"; } 2>/dev/null
  if [ -n "$fd" ]; then
    printf '%s\n' "$json" >&$fd
    [ "$ec" -ne 0 ] && IFS= read -r -t 0.6 -u $fd reply
    exec {fd}>&-
  else
    (REMAN_CAPTURE=$cap "$__reman_hook" record --exit "$ec" --cwd "$PWD" --duration-ms "$dur" -- "$cmd" &) >/dev/null 2>&1
  fi
  if [[ $reply =~ \"suggest\":\{\"command\":\"(([^\"\\]|\\.)*)\" ]]; then
    local fix=${BASH_REMATCH[1]} lead="did you mean"
    fix=${fix//\\\"/\"}; fix=${fix//\\\\/\\}
    [[ $reply == *'"kind":"proven"'* ]] && lead="last time this failed you ran"
    [[ $reply == *'"kind":"same_error"'* ]] && lead="the same error was fixed by"
    __reman_fix=$fix
    # what it changes, when it's a variant of what failed (adds --build, gti -> git)
    local how=$__reman_fix_hint
    if [[ $reply =~ \"diff\":\"(([^\"\\]|\\.)*)\" ]]; then how="${BASH_REMATCH[1]}; $how"; fi
    printf '\e[90m  reman: %s -> \e[36m%s\e[90m   (%s)\e[0m\n' "$lead" "$fix" "$how" >&2
  fi
  __reman_note "$reply" note   # it used to work here: what ran here since
  return $ec
}

trap '__reman_preexec' DEBUG
PROMPT_COMMAND="__reman_precmd${PROMPT_COMMAND:+; $PROMPT_COMMAND}"

__reman_find() {
  local scope=${1:-all} picked
  picked=$(REMAN_FIND_QUERY="$READLINE_LINE" "$__reman_exe" find --scope "$scope" --cwd "$PWD")
  if [ -n "$picked" ]; then
    READLINE_LINE="${picked//$'\x01'/}"
    READLINE_POINT=${#READLINE_LINE}
    # a command with a blank: \x01 marks where the cursor goes
    if [[ $picked == *$'\x01'* ]]; then
      local pre=${picked%%$'\x01'*}
      READLINE_POINT=${#pre}
    fi
  fi
}
__reman_insert_fix() {
  if [ -z "$__reman_fix" ]; then
    # no fix waiting: readline's forward-word (bind -x can't call it, so it's done here)
    local rest=${READLINE_LINE:READLINE_POINT}
    local skip=${rest%%[[:alnum:]]*}
    rest=${rest:${#skip}}
    local word=${rest%%[^[:alnum:]]*}
    READLINE_POINT=$((READLINE_POINT + ${#skip} + ${#word}))
    return
  fi
  READLINE_LINE="$__reman_fix"
  READLINE_POINT=${#READLINE_LINE}
}
# Alt-N on an empty line: what you'd run next here, ready to edit (Alt-N again: the next idea, up
# to 3)
__reman_nextup() {
  local i=0 fd= reply=
  if [ -n "${READLINE_LINE//[[:space:]]/}" ]; then
    [ -n "$__reman_next" ] && [ "$READLINE_LINE" = "$__reman_next" ] || return
    i=$(( __reman_next_i + 1 ))
  fi
  __reman_q "$PWD"; local qd=$REPLY
  __reman_q "$REMAN_SESSION"; local qs=$REPLY
  { exec {fd}<>"/dev/tcp/127.0.0.1/$__reman_port"; } 2>/dev/null || return
  printf '%s\n' "{\"op\":\"nextup\",\"cwd\":$qd,\"session\":$qs,\"index\":$i}" >&$fd
  IFS= read -r -t 0.4 -u $fd reply
  exec {fd}>&-
  if [[ $reply =~ \"command\":\"(([^\"\\]|\\.)*)\" ]]; then
    local c=${BASH_REMATCH[1]}
    c=${c//\\\"/\"}; c=${c//\\\\/\\}
    __reman_next=$c
    [[ $reply =~ \"index\":([0-9]+) ]] && __reman_next_i=${BASH_REMATCH[1]}
    READLINE_LINE=$c
    READLINE_POINT=${#READLINE_LINE}
  fi
}
# Tab on an EMPTY line opens the finder (readline's empty-line completion hook); Tab after text
# stays normal completion.
__reman_tab_empty() {
  local picked
  picked=$("$__reman_exe" find --scope folder --cwd "$PWD")
  COMPREPLY=()
  # (completion can't place the cursor: a blank's marker is just dropped)
  [ -n "$picked" ] && COMPREPLY=("${picked//$'\x01'/}")
}

# Tab completion for reman itself (the same engine every shell uses: `reman complete`). reman
# splits the line itself, so `D:\x` isn't broken at the colon by COMP_WORDBREAKS.
__reman_complete() {
  local before=${COMP_LINE:0:COMP_POINT}
  local partial=${before##*[[:space:]]}
  local cw=${COMP_WORDS[COMP_CWORD]}
  local pre=${partial%"$cw"}   # what readline split off the current word (e.g. `D:`)
  local IFS=$'\n' l v out
  out=$("$__reman_exe" complete "--line=${before%"$partial"}" "--cur=$partial" 2>/dev/null)
  COMPREPLY=()
  for l in $out; do
    v=${l%%$'\t'*}
    [[ $v == *[[:space:]]* ]] && v=$(printf '%q' "$v")   # a whole command stays one argument
    COMPREPLY+=("${v#"$pre"}")
  done
  # folders: no trailing space, so you can keep going into them
  if (( ${#COMPREPLY[@]} )) && [[ ${COMPREPLY[0]} == */ || ${COMPREPLY[0]} == *\\ ]]; then compopt -o nospace 2>/dev/null; fi
}
complete -F __reman_complete reman reman.exe

# reman's keys, given back what they did before when reman stops using one (readline's own
# functions, read once from `bind -p` into a file: no subshell)
declare -gA __reman_seq_prev 2>/dev/null
__reman_bindx() {
  if [ -z "$__reman_rl_read" ]; then
    __reman_rl_read=1
    bind -p > "$__reman_histfile" 2>/dev/null && mapfile -t __reman_rl_before < "$__reman_histfile"
  fi
  if [ -z "${__reman_seq_prev[$1]+x}" ]; then
    local l prev=
    for l in "${__reman_rl_before[@]}"; do
      [[ $l == "\"$1\": "* ]] && { prev=${l#*\": }; break; }
    done
    __reman_seq_prev[$1]=$prev
  fi
  bind -x "\"$1\": $2"
}
__reman_unbind_all() {
  local s
  for s in "${!__reman_seq_prev[@]}"; do
    bind -r "$s" 2>/dev/null
    [ -n "${__reman_seq_prev[$s]}" ] && bind "\"$s\": ${__reman_seq_prev[$s]}" 2>/dev/null
  done
  __reman_seq_prev=()
  [ -n "$__reman_tab_on" ] && complete -r -E 2>/dev/null
  __reman_tab_on=
}
# reman's keys changed in `reman settings`: taken up at the next prompt (one file-time test)
__reman_config="__CONFIG__"
__reman_keystamp="${TMPDIR:-/tmp}/.reman-keys-$$"
: >| "$__reman_keystamp" 2>/dev/null
__reman_keys_reload() {
  [[ $__reman_config -nt $__reman_keystamp ]] || return 0
  : >| "$__reman_keystamp" 2>/dev/null
  eval "$("$__reman_exe" keys --print bash 2>/dev/null)"
}
# (after reman's own, which reads the exit code first)
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND; }__reman_keys_reload"
# reman's keys (`reman settings`, Keys)
__KEYS__
