# reman shell integration for bash (generated by `reman init bash`).
# Captures cmd + cwd + exit + duration + session; Ctrl-R / Up open the native finder.
__reman_exe="__REMAN__"
reman() { "$__reman_exe" "$@"; }
[ -z "$REMAN_SESSION" ] && export REMAN_SESSION="$(cat /proc/sys/kernel/random/uuid 2>/dev/null || date +%s%N)-$$"

__reman_now_ms() { if [ -n "$EPOCHREALTIME" ]; then local t=${EPOCHREALTIME/[.,]/}; echo $(( t / 1000 )); else date +%s000; fi; }

__reman_preexec() {
  [ -n "$COMP_LINE" ] && return
  [ -n "$__reman_start" ] && return
  __reman_start=$(__reman_now_ms)
}

__reman_precmd() {
  local ec=$?
  local start=$__reman_start; __reman_start=
  local line; line=$(HISTTIMEFORMAT= builtin history 1)
  local num=${line%%[^ 0-9]*}; num=${num// /}
  [ -z "$start" ] && return $ec
  [ "$num" = "$__reman_last_num" ] && return $ec
  __reman_last_num=$num
  local cmd; cmd=$(sed -E 's/^ *[0-9]+\*? *//' <<< "$line")
  [ -z "$cmd" ] && return $ec
  local dur=$(( $(__reman_now_ms) - start ))
  if [ "$ec" -ne 0 ]; then
    "$__reman_exe" record --exit "$ec" --cwd "$PWD" --duration-ms "$dur" --suggest -- "$cmd"
  else
    ("$__reman_exe" record --exit "$ec" --cwd "$PWD" --duration-ms "$dur" -- "$cmd" &) 2>/dev/null
  fi
  return $ec
}

trap '__reman_preexec' DEBUG
PROMPT_COMMAND="__reman_precmd${PROMPT_COMMAND:+; $PROMPT_COMMAND}"

__reman_find() {
  local scope=${1:-all}
  local picked
  picked=$(REMAN_FIND_QUERY="$READLINE_LINE" "$__reman_exe" find --scope "$scope" --cwd "$PWD")
  if [ -n "$picked" ]; then
    READLINE_LINE="$picked"
    READLINE_POINT=${#READLINE_LINE}
  fi
}
bind -x '"\C-r": __reman_find all'
bind -x '"\e[A": __reman_find folder'
