-- reman shell integration for Command Prompt (cmd.exe) via Clink - generated by `reman init cmd`.
-- Clink loads every .lua file in its profile folder; `reman setup` puts a small loader there that
-- runs `reman init cmd`, so an updated reman is picked up by every new cmd window.
--   Records every command with its folder, real %ERRORLEVEL%, duration and session
--   Up = finder scoped to this folder   Ctrl+R = finder over all folders   Alt+F = insert the fix
--   Alt+N on an empty line = what you usually run next here (again: the next idea)
--   Tab on `reman ...` = reman's own completions (the same engine as the other shells)
-- cmd's quoting can't carry arbitrary text intact (" & | % ^), so text travels to reman through
-- environment variables, never the command line.

local exe = [[__REMAN__]]
local hook = [[__HOOK__]]
local spool = [[__SPOOL__]]

-- `reman` on PATH
local bindir = exe:match("^(.*)[\\/]")
if bindir and not (";" .. (os.getenv("PATH") or ""):lower() .. ";"):find(";" .. bindir:lower() .. ";", 1, true) then
    os.setenv("PATH", bindir .. ";" .. (os.getenv("PATH") or ""))
end

-- one session per cmd.exe (never inherited from whatever started it)
local session = "cmd-" .. os.getpid() .. "-" .. os.time()
os.setenv("REMAN_SESSION", session)

local function json_str(s)
    s = s:gsub('[%c"\\]', function(c)
        if c == '"' then return '\\"' elseif c == "\\" then return "\\\\"
        elseif c == "\n" then return "\\n" elseif c == "\r" then return "\\r" elseif c == "\t" then return "\\t"
        else return string.format("\\u%04x", c:byte()) end
    end)
    return '"' .. s .. '"'
end

-- run a reman program with some environment variables set only for that call
local function with_env(vars, fn)
    local old = {}
    for k, v in pairs(vars) do old[k] = os.getenv(k) or false; os.setenv(k, v) end
    local ok, r = pcall(fn)
    -- (false marks "was unset": pairs() would skip a nil and leave the variable behind)
    for k, v in pairs(old) do os.setenv(k, v or nil) end
    return ok and r or nil
end

-- ---- capture -----------------------------------------------------------------------------------
local pending = nil
reman_fix = reman_fix or nil

clink.onendedit(function(line)
    pending = nil
    -- a leading space keeps a command out of history (same rule as every other shell)
    if line and line:sub(1, 1) ~= " " and #(line:gsub("%s", "")) > 1 then
        pending = { cmd = line, t = os.clock(), ts = os.time() }
    end
end)

-- cmd's built-ins (echo, cls, title, ...) never reset %ERRORLEVEL%, so after one failure every
-- later `echo` would look failed too. `(call )` sets it to 0 first. Lines that read the
-- errorlevel themselves (`if errorlevel 1 ...`) are left exactly as typed.
if clink.onfilterinput then
    clink.onfilterinput(function(line)
        if line and line:match("%S") and not line:lower():find("errorlevel", 1, true) then
            return "(call ) & " .. line
        end
    end)
end

clink.onbeginedit(function()
    local p = pending
    pending = nil
    if not p then return end
    local code = os.geterrorlevel() or 0
    local dur = math.floor((os.clock() - p.t) * 1000)
    local cwd = os.getcwd()
    if code == 0 then
        -- success: one line appended to the spool (no process), the daemon drains it within a second
        local f = io.open(spool, "a")
        if f then
            f:write('{"op":"ingest","command":' .. json_str(p.cmd) .. ',"exit":0,"cwd":' .. json_str(cwd)
                .. ',"session":' .. json_str(session) .. ',"actor":"human","ts":' .. p.ts .. ',"duration_ms":' .. dur .. '}\n')
            f:close()
        end
        return
    end
    -- failure: record through the hook and show what worked last time
    local out = with_env({ REMAN_RECORD_CMD = p.cmd }, function()
        local h = io.popen('""' .. hook .. '" record --exit ' .. code .. ' --duration-ms ' .. dur
            .. ' --session ' .. session .. ' --actor human --suggest --print-fix 2>&1"')
        if not h then return nil end
        local s = h:read("*a")
        h:close()
        return s
    end)
    reman_fix = nil
    if out and #out > 0 then
        for l in out:gmatch("[^\r\n]+") do
            if l:find("reman:", 1, true) then
                clink.print(l .. "\x1b[90m   (__FIX_HINT__)\x1b[0m")
            elseif not l:find("\x1b", 1, true) then
                reman_fix = l
            end
        end
    end
end)

-- ---- finder ------------------------------------------------------------------------------------
local function find(rl_buffer, scope)
    local tmp = (os.getenv("TEMP") or ".") .. "\\reman-pick-" .. os.getpid() .. ".txt"
    os.remove(tmp)
    with_env({ REMAN_FIND_QUERY = rl_buffer:getbuffer() }, function()
        os.execute('""' .. exe .. '" find --scope ' .. scope .. ' --cwd "' .. os.getcwd() .. '" --result-file "' .. tmp .. '""')
    end)
    local f = io.open(tmp, "rb")
    local pick = f and f:read("*a") or ""
    if f then f:close() end
    os.remove(tmp)
    pick = pick:gsub("[\r\n]+$", "")
    if #pick > 0 then
        -- a command with a blank: \1 marks where the cursor goes
        local at = pick:find("\1", 1, true)
        rl_buffer:beginundogroup()
        rl_buffer:remove(1, rl_buffer:getlength() + 1)
        rl_buffer:insert((pick:gsub("\1", "")))
        rl_buffer:endundogroup()
        if at then rl_buffer:setcursor(at) end
    end
    rl_buffer:refreshline()
end

function reman_find_folder(rl_buffer) find(rl_buffer, "folder") end
function reman_find_all(rl_buffer) find(rl_buffer, "all") end
function reman_insert_fix(rl_buffer)
    if reman_fix then
        rl_buffer:beginundogroup()
        rl_buffer:remove(1, rl_buffer:getlength() + 1)
        rl_buffer:insert(reman_fix)
        rl_buffer:endundogroup()
    elseif not (rl.invokecommand and pcall(rl.invokecommand, "forward-word")) then
        -- no fix waiting: what Alt+F does without reman (it also accepts a word of a suggestion)
        rl_buffer:ding()
    end
end

-- Alt+N on an empty line: what you'd run next here, ready to edit (Alt+N again: the next idea,
-- up to 3)
reman_next, reman_next_i = nil, 0
function reman_nextup(rl_buffer)
    local line = rl_buffer:getbuffer()
    local i = 0
    if line:match("%S") then
        if not reman_next or line ~= reman_next then return rl_buffer:ding() end
        i = reman_next_i + 1
    end
    local h = io.popen('""' .. hook .. '" nextup --cwd "' .. os.getcwd() .. '" --session ' .. session .. ' --index ' .. i .. '"')
    local out = h and h:read("*l") or ""
    if h then h:close() end
    local cmd, why, idx = out:match("^([^\t]*)\t([^\t]*)\t(%d+)")
    if not cmd or cmd == "" then return rl_buffer:ding() end
    reman_next, reman_next_i = cmd, tonumber(idx) or 0
    if i == 0 then
        clink.print("\x1b[90m  reman: " .. why .. "\x1b[0m")
    end
    rl_buffer:beginundogroup()
    rl_buffer:remove(1, rl_buffer:getlength() + 1)
    rl_buffer:insert(cmd)
    rl_buffer:endundogroup()
    rl_buffer:refreshline()
end

-- reman's keys (`reman settings`, Keys)
__KEYS__

-- ---- Tab completion for reman itself -----------------------------------------------------------
local gen = clink.generator(1)
function gen:generate(line_state, builder)
    local line = line_state:getline():sub(1, line_state:getcursor() - 1)
    if not line:lower():match("^%s*reman[%.exe]*%s") then return false end
    -- the word being completed, from the text itself: Clink may call this before the word has
    -- any letters (it caches matches per word), and getendword() can lag behind the typing
    local word = line:match("(%S*)$") or ""
    local head = line:sub(1, #line - #word)
    -- ask again as the word grows, so "your own commands" stay filtered by what's typed
    if builder.setvolatile then builder:setvolatile() end
    local out = with_env({ REMAN_COMPLETE_LINE = head, REMAN_COMPLETE_CUR = word }, function()
        local h = io.popen('""' .. exe .. '" complete 2>nul"')
        if not h then return nil end
        local s = h:read("*a")
        h:close()
        return s
    end)
    for l in (out or ""):gmatch("[^\r\n]+") do
        local v, d = l:match("^([^\t]*)\t?(.*)$")
        if v and #v > 0 then
            builder:addmatch({ match = v, description = d ~= "" and d or nil, type = v:sub(-1):match("[\\/]") and "dir" or "arg" })
        end
    end
    return true
end
