# reman shell integration for fish (generated by `reman init fish`).
# fish has no TCP builtin. Successes are appended to reman's spool file using builtins only
# (no process at all; the daemon drains it every second). A failure runs the slim reman-hook
# (no ONNX, ~2MB) and waits briefly for the fix suggestion.
#   Up = finder (this folder)   Ctrl-R = finder (all folders)   Alt-F = insert suggested fix
#   Enter on a command that keeps failing here = held once, with why (Enter again runs it)
#   Alt-N on an empty line = what you usually run next here (again: the next idea)
#   Tab on an empty line = finder (Tab after text is normal completion)
set -g __reman_exe "__REMAN__"
set -g __reman_hook "__HOOK__"
set -g __reman_spool "__SPOOL__"
# `reman settings` can open every shell inside `reman shell`, so what your commands print is kept
# too: this one hands over to a shell inside it, and closes when that one does (it goes on as
# usual when that can't start)
if test __SHELL_LAYER__ = 1; and not set -q REMAN_PTY; and status is-interactive; and isatty stdin; and test "$TERM_PROGRAM" != vscode
    $__reman_exe shell -- (status fish-path) -i
    set -l s $status
    test $s -ne 97; and exit $s
end
# MSYS2/Cygwin fish can run C:/ paths but can't redirect into them: use the POSIX form
if string match -qr '^[A-Za-z]:' -- $__reman_spool; and command -q cygpath
    set __reman_spool (cygpath -u -- $__reman_spool)
end
function reman; $__reman_exe $argv; end
# rcd <words>: go to the folder where you ran what the words describe (or whose path has them).
# `rcd alembic 2` takes the second match; `rcd` lists where you were lately, `rcd 3` goes there.
function rcd
    set -l p ($__reman_exe goto $argv); or return
    test -n "$p"; or return
    command -q cygpath; and set p (cygpath -u $p)
    cd $p
end
# one session per shell: the id lives in an unexported variable, so a child shell makes its own
if not set -q __reman_sid
    set -g __reman_sid fish-$fish_pid-(random)(random)
end
set -gx REMAN_SESSION $__reman_sid

# warm the daemon once per shell (it drains the spool and answers the finder)
$__reman_exe ping >/dev/null 2>&1 &
disown 2>/dev/null

# JSON-quote $argv into $__reman_qv. One builtin pipeline, result in a global: calling a FUNCTION
# inside a command substitution costs ~50ms on MSYS fish, builtins ~1ms.
function __reman_q
    set -l s (string replace -a -- '\\' '\\\\' $argv | string replace -a -- '"' '\\"' | string replace -a -- \t '\\t' | string replace -a -- \r '\\r')
    set -g __reman_qv '"'(string join '\n' -- $s)'"'
end

# (on Windows the terminal reman shell runs is ConPTY, which draws text on its own beat but
# passes a mark on at once: a mark waits one beat, so it lands after what came before it)
if set -q REMAN_PTY; and string match -qr '^(MSYS|CYGWIN|MINGW)' -- (uname -s)
    set -g __reman_conpty 1
end
function __reman_beat
    set -q __reman_conpty; and sleep 0.03
end

# inside `reman shell`, what the command prints is kept: it starts here (the prompt ends it)
function __reman_preexec --on-event fish_preexec
    set -q REMAN_PTY; or return
    test -n (string trim -- "$argv[1]"); or return
    set -g __reman_cap "$REMAN_SESSION-"(date +%s)(random)
    __reman_beat
    printf '\e]46031711;C;%s\a' $__reman_cap >/dev/tty 2>/dev/null
end

function __reman_postexec --on-event fish_postexec
    set -l ec $status
    set -l cmd $argv[1]
    set -l cap $__reman_cap
    set -g __reman_cap
    if test -n "$cap"
        __reman_beat
        printf '\e]46031711;D;%s\a' $cap >/dev/tty 2>/dev/null
    end
    test -z "$cmd"; and return
    string match -q -- ' *' $cmd; and return   # leading space: never recorded
    set -g __reman_fix   # a fix is offered for the command just run, until the next one
    if test $ec -ne 0
        set -g __reman_fix (env REMAN_CAPTURE="$cap" $__reman_hook record --exit $ec --cwd $PWD --duration-ms $CMD_DURATION --suggest --print-fix -- $cmd)
    else
        __reman_q $cmd; set -l qc $__reman_qv
        __reman_q $PWD; set -l qd $__reman_qv
        __reman_q $REMAN_SESSION; set -l qs $__reman_qv
        # (an empty string, not an empty list: joined to an empty list, fish drops the whole line)
        set -l qcap ''
        test -n "$cap"; and set qcap ',"capture":"'$cap'"'
        echo '{"op":"ingest","command":'$qc',"exit":'$ec',"cwd":'$qd',"session":'$qs',"actor":"human","duration_ms":'$CMD_DURATION$qcap'}' >>$__reman_spool
    end
end

# "last time here": asked when the folder changes (the daemon answers once per session and folder)
function __reman_welcome --on-variable PWD
    $__reman_hook welcome --cwd $PWD --session $REMAN_SESSION
end
__reman_welcome

function __reman_find
    set -l scope $argv[1]
    set -l picked (env REMAN_FIND_QUERY=(commandline) $__reman_exe find --scope $scope --cwd $PWD)
    if test -n "$picked"
        # a command with a blank: \x01 marks where the cursor goes
        set -l parts (string split -m 1 \x01 -- "$picked")
        commandline -r -- (string join '' -- $parts)
        test (count $parts) -eq 2; and commandline -C (string length -- "$parts[1]")
    end
    commandline -f repaint
end

function __reman_insert_fix
    if test -n "$__reman_fix"
        commandline -r -- $__reman_fix
    else
        # what Alt-F does without reman: forward-word, which also accepts one word of the
        # autosuggestion
        commandline -f forward-word
    end
end

# Enter: a command that keeps failing here is held once, with why (and the fix, on Alt-F); Enter
# again runs it
function __reman_enter
    set -l line (commandline)
    set -l t (string trim -- "$line")
    if test (count $line) -eq 1; and test (string length -- "$t") -gt 1; and not string match -q -- ' *' "$line"; and test "$t" != "$__reman_held"
        set -l out ($__reman_hook precheck --cwd $PWD -- $t 2>/dev/null)
        if test -n "$out"
            set -l parts (string split -m 3 \t -- $out[1])
            set -g __reman_held $t
            echo
            set_color yellow; echo "  reman: $parts[1]"; set_color normal
            if test -n "$parts[3]"
                set_color brblack; echo "         last error: $parts[3]"; set_color normal
            end
            if test -n "$parts[2]"
                set -g __reman_fix $parts[2]
                set -l how "Alt-F inserts"
                test -n "$parts[4]"; and set how "$parts[4]; $how"
                set_color brblack; echo -n "  reman: worked instead -> "; set_color cyan; echo -n $parts[2]; set_color brblack; echo "   ($how)"; set_color normal
            end
            set_color brblack; echo "  Enter again runs it anyway"; set_color normal
            commandline -f repaint
            return
        end
    end
    set -g __reman_held
    commandline -f execute
end

# Alt-N on an empty line: what you'd run next here, ready to edit (Alt-N again: the next idea, up
# to 3)
function __reman_nextup
    set -l line (commandline)
    set -l i 0
    if test -n (string trim -- "$line")
        test -n "$__reman_next"; and test "$line" = "$__reman_next"; or return
        set i (math $__reman_next_i + 1)
    end
    set -l out ($__reman_hook nextup --cwd $PWD --session $REMAN_SESSION --index $i 2>/dev/null)
    test -n "$out"; or return
    set -l parts (string split \t -- $out[1])
    set -g __reman_next $parts[1]
    set -g __reman_next_i $parts[3]
    if test $i -eq 0
        echo
        set_color brblack; echo "  reman: $parts[2]"; set_color normal
    end
    commandline -r -- $parts[1]
    commandline -f repaint
end

# a held command is held once per prompt
function __reman_unhold --on-event fish_postexec --on-event fish_cancel
    set -g __reman_held
end

function __reman_tab
    if test -z (commandline)
        __reman_find folder
    else
        commandline -f complete
    end
end

bind \t __reman_tab

# Tab completion for reman itself (the same engine every shell uses: `reman complete`);
# fish reads `value<TAB>description` natively
function __reman_complete
    $__reman_exe complete "--line="(string join ' ' -- (commandline -opc))" " "--cur="(commandline -ct) 2>/dev/null
end
complete -c reman -f -a '(__reman_complete)'
complete -c reman.exe -f -a '(__reman_complete)'
bind \cr '__reman_find all'
bind \e\[A '__reman_find folder'
bind \ef __reman_insert_fix
bind \r __reman_enter
bind \en __reman_nextup
