# reman shell integration (generated by `reman init powershell`). Replaces Atuin: captures every
# command with cwd + real exit code + duration + session, and binds the native finder.
#   UpArrow = finder scoped to this folder   Ctrl+R = finder over all folders   Alt+F = insert fix
#   Enter on a command that keeps failing here = held once, with why (Enter again runs it)
#   Alt+N on an empty line = what you usually run next here (again: the next idea)
#   Tab = normal completion; when there's nothing to complete, the grey prediction, else the finder
$global:__RemanExe = "__REMAN__"
# `reman settings` can open every shell inside `reman shell`, so what your commands print is kept
# too: this one hands over to a shell inside it, and closes when that one does (it goes on as
# usual when that can't start). Only an interactive console shell, never one already inside.
if (__SHELL_LAYER__ -and $null -eq $global:__RemanLevels -and -not $env:REMAN_PTY -and $Host.Name -eq 'ConsoleHost' -and $env:TERM_PROGRAM -ne 'vscode' -and
    -not [Console]::IsInputRedirected -and -not ([Environment]::GetCommandLineArgs() | Where-Object { $_ -match '^-(c|command|f|file|e|ec|encodedcommand)$' })) {
  # the same PowerShell, started the same way
  $__remanArgs = @([Environment]::GetCommandLineArgs() | Select-Object -Skip 1)
  if (-not ($__remanArgs -match '^-nologo$')) { $__remanArgs += '-NoLogo' }
  & $global:__RemanExe shell -- (Get-Process -Id $PID).Path @__remanArgs
  if ($LASTEXITCODE -ne 97) { [Environment]::Exit($LASTEXITCODE) }
}
# `reman` is the exe on PATH, not a wrapper function: PowerShell only gives native commands
# their argument completer (below)
$__remanDir = Split-Path -Parent $global:__RemanExe
if (($env:PATH -split ';') -notcontains $__remanDir) { $env:PATH = "$__remanDir;$env:PATH" }
Remove-Item Function:\reman -ErrorAction SilentlyContinue

# Tab completion for reman itself - the same engine as bash / zsh / fish (`reman complete`):
# subcommands and flags with their help, agents with their status, folders you could share,
# your own commands for forget / pin / check / fixes.
Register-ArgumentCompleter -Native -CommandName 'reman', 'reman.exe' -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $text = $commandAst.ToString()
  $upto = [Math]::Min([Math]::Max($cursorPosition - $commandAst.Extent.StartOffset, 0), $text.Length)
  $before = $text.Substring(0, $upto)
  $head = $before.Substring(0, $before.Length - [Math]::Min($wordToComplete.Length, $before.Length))
  $enc = [Console]::OutputEncoding
  try {
    [Console]::OutputEncoding = [Text.Encoding]::UTF8
    $lines = & $global:__RemanExe complete "--line=$head" "--cur=$wordToComplete" 2>$null
  } finally { [Console]::OutputEncoding = $enc }
  foreach ($l in @($lines)) {
    if (-not $l) { continue }
    $v, $d = $l -split "`t", 2
    $insert = if ($v -match "[\s'`"``$;&|(){}@#,]") { "'" + ($v -replace "'", "''") + "'" } else { $v }
    $type = if ($v.StartsWith('-')) { 'ParameterName' } else { 'ParameterValue' }
    [System.Management.Automation.CompletionResult]::new($insert, $v, $type, $(if ($d) { $d } else { $v }))
  }
}
# One session per shell. Never inherited: a window (or VS Code) started from this one is a
# different shell, and flows / "last command failed" are per shell.
if (-not $global:__RemanSessionId) { $global:__RemanSessionId = [guid]::NewGuid().ToString() }
$env:REMAN_SESSION = $global:__RemanSessionId

# One JSON line to the daemon. $waitMs > 0 waits (bounded) for the reply. If the daemon is down the
# run goes to the spool file (drained on next start) and the daemon is started in the background.
function global:__RemanSend {
  param($obj, [int]$waitMs = 0, [bool]$spool = $true, [int]$connectMs = 250)
  $json = ($obj | ConvertTo-Json -Compress)
  try {
    $c = New-Object Net.Sockets.TcpClient
    $iar = $c.BeginConnect('127.0.0.1', __PORT__, $null, $null)
    if (-not $iar.AsyncWaitHandle.WaitOne($connectMs)) { $c.Close(); throw 'reman daemon down' }
    $c.EndConnect($iar)
    $st = $c.GetStream()
    $b = [Text.Encoding]::UTF8.GetBytes($json + "`n")
    $st.Write($b, 0, $b.Length); $st.Flush()
    $resp = $null
    if ($waitMs -gt 0) {
      $st.ReadTimeout = $waitMs
      try { $resp = (New-Object IO.StreamReader($st, [Text.Encoding]::UTF8)).ReadLine() | ConvertFrom-Json } catch { }
    }
    $c.Close()
    return $resp
  } catch {
    if (-not $spool) { return $null }
    try { [IO.File]::AppendAllText("__SPOOL__", $json + "`n", (New-Object Text.UTF8Encoding($false))) } catch { }
    $now = [DateTime]::UtcNow
    if (-not $global:__RemanSpawned -or ($now - $global:__RemanSpawned).TotalSeconds -gt 30) {
      $global:__RemanSpawned = $now
      try { Start-Process -FilePath $global:__RemanExe -ArgumentList 'daemon' -WindowStyle Hidden } catch { }
    }
    return $null
  }
}

# Warm the daemon when the shell starts (non-blocking), so the very first failure already gets a
# suggestion instead of landing in the spool.
try {
  $__c = New-Object Net.Sockets.TcpClient
  $__iar = $__c.BeginConnect('127.0.0.1', __PORT__, $null, $null)
  if (-not $__iar.AsyncWaitHandle.WaitOne(150)) {
    $global:__RemanSpawned = [DateTime]::UtcNow
    Start-Process -FilePath $global:__RemanExe -ArgumentList 'daemon' -WindowStyle Hidden
  }
  $__c.Close()
} catch { }

# ---- Capture ---------------------------------------------------------------------------------
# Whether a command failed is in `$?`, and only the FIRST statement of the prompt can read it -
# any statement before it resets it to True. So reman's prompt must run first. Tools that wrap
# the prompt after reman loads (a Python venv's Activate.ps1, conda, VS Code's shell integration)
# would run their own code first and turn every failure into a success. When one wraps us, we
# step back outside it and call it from there, handing it the real `$?`; when it unwinds (a
# venv's `deactivate` puts an older prompt back) we drop it again.
#   __RemanChain  wrappers installed after us, newest first
#   __RemanLevels the prompt object we installed at each chain depth (identity = "we're outermost")
#   __RemanDepth  $null outside a prompt; how deep the current prompt walk is

# Record the command that just finished (once: repeated prompts see the same history id).
# $trusted = we read `$?` first. Otherwise judge from what the command left behind.
function global:__RemanWelcome {
  # "last time here": asked when the folder changes; the daemon answers once per session and
  # folder, and only after a while away
  try {
    $here = (Get-Location).Path
    if ($here -eq $global:__RemanPwd) { return }
    $global:__RemanPwd = $here
    $r = __RemanSend @{ op = 'welcome'; cwd = $here; session = $env:REMAN_SESSION } 300 $false
    if ($r -and $r.line) { Write-Host "  reman: $($r.line)" -ForegroundColor DarkGray }
  } catch { }
}

function global:__RemanCapture {
  param([bool]$ok, $code, [bool]$trusted)
  try {
    $e0 = if ($global:Error.Count) { $global:Error[0] } else { $null }
    $h = Get-History -Count 1
    if ($h -and $h.Id -ne $global:__RemanLastHistId) {
      $global:__RemanLastHistId = $h.Id
      $global:__RemanFix = $null   # a fix is offered for the command just run, until the next one
      $newErr = $e0 -and -not [object]::ReferenceEquals($e0, $global:__RemanErr0)
      if (-not $trusted) {
        $ok = ($h.ExecutionStatus -eq 'Completed') -and -not $newErr -and -not ($code -and $code -ne $global:__RemanPrevCode)
      }
      $cmd = $h.CommandLine
      if ($cmd -and -not $cmd.StartsWith(' ') -and $cmd.Trim().Length -gt 1) {
        $exit = if ($ok) { 0 } elseif ($code) { $code } else { 1 }
        $dur = [int64]($h.EndExecutionTime - $h.StartExecutionTime).TotalMilliseconds
        $req = @{ op = 'ingest'; command = $cmd; exit = $exit; cwd = (Get-Location).Path;
                  session = $env:REMAN_SESSION; actor = 'human'; duration_ms = $dur }
        # `reman shell` sends what it printed under this id
        if ($global:__RemanCapId) { $req.capture = $global:__RemanCapId }
        if ($exit -ne 0) {
          # what it printed, when PowerShell kept it (cmdlets; a native program's stderr isn't)
          if ($newErr) { try { $req.error = [string]$e0.Exception.Message } catch { } }
          $r = __RemanSend $req 400
          if ($r -and $r.suggest -and $r.suggest.command) {
            $global:__RemanFix = [string]$r.suggest.command
            $lead = switch ($r.suggest.kind) { 'proven' { 'last time this failed you ran' } 'same_error' { 'the same error was fixed by' } default { 'did you mean' } }
            Write-Host "  reman: $lead -> " -NoNewline -ForegroundColor DarkGray
            Write-Host $global:__RemanFix -NoNewline -ForegroundColor Cyan
            # what it changes, when it's a variant of what failed (adds --build, gti -> git)
            $how = if ($r.suggest.diff) { "   ($($r.suggest.diff); $global:__RemanFixHint)" } else { "   ($global:__RemanFixHint)" }
            Write-Host $how -ForegroundColor DarkGray
          }
          # it used to work here: what ran here since
          if ($r -and $r.note) { Write-Host "  reman: $($r.note)" -ForegroundColor DarkGray }
        } else { [void](__RemanSend $req 0) }
      }
    }
    $global:__RemanErr0 = $e0
    $global:__RemanPrevCode = $code
  } catch { }
}

function global:__RemanBasePrompt {
  if ($global:__RemanBase) { & $global:__RemanBase }
  else { "PS $($executionContext.SessionState.Path.CurrentLocation)$('>' * ($nestedPromptLevel + 1)) " }
}

# An updated reman reloads itself into open shells at the next prompt (one file-time check).
function global:__RemanAutoReload {
  try {
    $t = [IO.File]::GetLastWriteTimeUtc($global:__RemanExe)
    if ($global:__RemanExeTime -and $t -ne $global:__RemanExeTime) {
      $global:__RemanExeTime = $t
      . ([scriptblock]::Create((& $global:__RemanExe init powershell | Out-String)))
      Write-Host '  reman: updated - this shell now runs the new version' -ForegroundColor DarkGray
      return
    }
    # the keys changed in `reman settings`: this shell takes them up (one file-time check)
    $c = [IO.File]::GetLastWriteTimeUtc($global:__RemanConfig)
    if ($global:__RemanConfigTime -and $c -ne $global:__RemanConfigTime) {
      $global:__RemanConfigTime = $c
      $keys = (& $global:__RemanExe keys --print powershell | Out-String)
      if ($keys.Trim()) { . ([scriptblock]::Create($keys)) }
    }
  } catch { }
}

$global:__RemanPrompt = {
  # reman-prompt
  $ok = $global:?
  $code = $global:LASTEXITCODE
  if ($null -ne $global:__RemanDepth) {
    # a wrapper is calling the prompt it wrapped: go one level further in, `$?` intact
    $d = ++$global:__RemanDepth
    $global:LASTEXITCODE = $code
    if (-not $ok) { Write-Error 'reman: the last command failed' -ErrorAction Ignore }
    if ($d -lt @($global:__RemanChain).Count) { & @($global:__RemanChain)[$d] } else { __RemanBasePrompt }
    return
  }
  $cur = $function:global:prompt
  $levels = @($global:__RemanLevels)
  $k = -1
  for ($i = $levels.Count - 1; $i -ge 0; $i--) { if ([object]::ReferenceEquals($cur, $levels[$i])) { $k = $i; break } }
  $trusted = $k -ge 0
  if ($trusted -and $k -lt $levels.Count - 1) {
    # an older prompt of ours is back (a venv's `deactivate`): the wrappers added since are gone
    $global:__RemanChain = @(@($global:__RemanChain) | Select-Object -Skip ($levels.Count - 1 - $k))
    $global:__RemanLevels = @($levels | Select-Object -First ($k + 1))
  }
  # (ConPTY draws text on its own beat but passes a mark on at once: a mark waits one beat, so
  # it lands after what came before it)
  if ($global:__RemanCapId) { Start-Sleep -Milliseconds 30; [Console]::Write("$([char]27)]46031711;D;$($global:__RemanCapId)$([char]7)") }
  __RemanCapture $ok $code $trusted
  $global:__RemanCapId = $null
  __RemanWelcome
  if ($trusted) { __RemanAutoReload }
  $global:__RemanDepth = 0
  try {
    $global:LASTEXITCODE = $code
    if (-not $ok) { Write-Error 'reman: the last command failed' -ErrorAction Ignore }
    $p = if (@($global:__RemanChain).Count) { & @($global:__RemanChain)[0] } else { __RemanBasePrompt }
    if ($global:__RemanOsc) {
      # OSC 133: the last command ended (with its code), a prompt starts, input starts
      $esc = [char]27; $bel = [char]7
      $d = if ($ok) { 0 } elseif ($code) { $code } else { 1 }
      "$esc]133;D;$d$bel$esc]133;A$bel" + ($p -join '') + "$esc]133;B$bel"
    } else { $p }
  } finally {
    $global:__RemanDepth = $null
    if (-not $trusted) {
      # something wrapped the prompt after reman: step back outside it, keeping it inside
      $global:__RemanChain = @($cur) + @($global:__RemanChain)
      $function:global:prompt = [scriptblock]::Create($global:__RemanPrompt.ToString())
      $global:__RemanLevels = @($global:__RemanLevels) + @($function:global:prompt)
    }
  }
}

if ($null -eq $global:__RemanLevels) {
  # first load in this shell: the prompt that exists now is the one we build on
  $global:__RemanBase = $function:prompt
  $global:__RemanChain = @()
  $global:__RemanLevels = @()
  $global:__RemanLastHistId = -1
}
$global:__RemanDepth = $null
$function:global:prompt = [scriptblock]::Create($global:__RemanPrompt.ToString())
if ($global:__RemanLevels.Count) { $global:__RemanLevels[$global:__RemanLevels.Count - 1] = $function:global:prompt }
else { $global:__RemanLevels = @($function:global:prompt) }
$global:__RemanExeTime = try { [IO.File]::GetLastWriteTimeUtc($global:__RemanExe) } catch { $null }
$global:__RemanConfig = "__CONFIG__"
$global:__RemanConfigTime = try { [IO.File]::GetLastWriteTimeUtc($global:__RemanConfig) } catch { $null }

# OSC 133 prompt marks, for terminals that show them (Windows Terminal, WezTerm): jump between
# commands, see each one's exit code. VS Code adds its own; REMAN_NO_OSC133 turns ours off.
$global:__RemanOsc = (-not $env:REMAN_NO_OSC133) -and ($env:TERM_PROGRAM -ne 'vscode') -and ($env:WT_SESSION -or $env:TERM_PROGRAM -eq 'WezTerm')

# PSReadLine reads each command line through PSConsoleHostReadLine. Wrapping it (as Atuin does)
# is a safety net for capture: if something replaced the prompt without calling reman's, the
# last command is still recorded here (__RemanCapture skips one it already has). It also marks
# where a command starts, for OSC 133.
if ((Get-Command PSConsoleHostReadLine -ErrorAction Ignore) -and -not $global:__RemanReadLine) {
  $global:__RemanReadLine = ${function:PSConsoleHostReadLine}
}
if ($global:__RemanReadLine) {
  function global:PSConsoleHostReadLine {
    try { __RemanCapture $true $global:LASTEXITCODE $false } catch { }
    $global:__RemanHeld = $null   # a held command is held once per line read
    $line = & $global:__RemanReadLine
    if ($global:__RemanOsc) { [Console]::Write("$([char]27)]133;C$([char]7)") }
    if ($env:REMAN_PTY -and $line -and $line.Trim()) {
      # inside `reman shell`, what the command prints is kept: it starts here (the prompt ends it)
      $global:__RemanCapId = "$env:REMAN_SESSION-$([DateTime]::UtcNow.Ticks)"
      Start-Sleep -Milliseconds 30
      [Console]::Write("$([char]27)]46031711;C;$($global:__RemanCapId)$([char]7)")
    }
    $line
  }
}

# rcd <words>: go to the folder where you ran what the words describe (or whose path has them).
# `rcd alembic 2` takes the second match; `rcd` lists where you were lately, `rcd 3` goes there.
# A function, since a program can't change its shell's folder (`reman` itself stays the exe).
function global:rcd {
  $p = & $global:__RemanExe goto @args
  if ($LASTEXITCODE -eq 0 -and $p) { Set-Location -LiteralPath (@($p)[-1]) }
}

# Put the finder's pick on the prompt. A command with a blank carries [char]1 where the cursor
# goes (`git commit -m "|"`).
function global:__RemanPut {
  param([string]$line, [string]$chosen)
  $at = $chosen.IndexOf([char]1)
  [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $chosen.Replace([string][char]1, ''))
  if ($at -ge 0) { [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($at) }
}

# Native finder. The query travels via env (Windows PowerShell 5.1 drops empty native args and
# mangles embedded quotes); the pick comes back through a temp file.
function global:__RemanFind {
  param([string]$line, [string]$scope)
  $tmp = [IO.Path]::GetTempFileName()
  $env:REMAN_FIND_QUERY = $line
  # the finder opens under the prompt and scrolls the screen up when the prompt sits low; it puts
  # the cursor back where the line starts, and PSReadLine is told where its prompt went
  $b = $null; $at = 0
  [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$b, [ref]$at)
  [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition(0)
  $top = [Console]::CursorTop
  try {
    & $global:__RemanExe find --scope $scope --cwd ((Get-Location).Path) --result-file $tmp
    $chosen = [IO.File]::ReadAllText($tmp, [Text.Encoding]::UTF8)
  } catch { $chosen = $null }
  finally { Remove-Item Env:\REMAN_FIND_QUERY -ErrorAction SilentlyContinue; Remove-Item $tmp -ErrorAction SilentlyContinue }
  if ([Console]::CursorTop -ne $top) {
    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt($null, [Math]::Max(0, [Console]::CursorTop - (Get-PSReadLineOption).ExtraPromptLineCount))
  }
  [Microsoft.PowerShell.PSConsoleReadLine]::SetCursorPosition($at)
  if ($chosen) { return $chosen.TrimEnd("`r", "`n") }
  return $null
}

if (Get-Module PSReadLine -ErrorAction SilentlyContinue) {
  # The finder for this folder (UpArrow unless `reman settings` says otherwise)
  function global:__RemanKeyFindHere {
    param($key, $arg)
    $line = $null; $cur = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
    $up = $key -and $key.Key -eq [ConsoleKey]::UpArrow -and $key.Modifiers -eq 0
    # a line of several lines, or predictions shown as a list: the key moves through those, as it
    # did before reman (an empty line still opens the finder)
    $o = Get-PSReadLineOption
    $list = $line -and "$($o.PredictionViewStyle)" -eq 'ListView' -and "$($o.PredictionSource)" -notin '', 'None'
    if ($line.Contains("`n") -or $list) {
      if ($up) {
        if ($line.Contains("`n")) { [Microsoft.PowerShell.PSConsoleReadLine]::PreviousLine() } else { [Microsoft.PowerShell.PSConsoleReadLine]::PreviousHistory($key, $arg) }
        return
      }
      if (__RemanPrev $key $arg) { return }
    }
    $chosen = __RemanFind $line 'folder'
    if ($chosen) { __RemanPut $line $chosen }
    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
  }
  # What the key that ran a handler did before reman took it (else what the action's first key did)
  function global:__RemanPrevOf($action) {
    $f = if ($global:__RemanChord -and $global:__RemanPrevKey) { $global:__RemanPrevKey[$global:__RemanChord] }
    if (-not $f -and $action -and $global:__RemanPrevFor) { $f = $global:__RemanPrevFor[$action] }
    $f
  }
  function global:__RemanPrev($key, $arg, $action) {
    $f = __RemanPrevOf $action
    if (-not $f) { return $false }
    [Microsoft.PowerShell.PSConsoleReadLine]::($f).Invoke($key, $arg)
    $true
  }
  # The finder for every folder (Ctrl+R)
  function global:__RemanKeyFindAll {
    param($key, $arg)
    $line = $null; $cur = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
    $chosen = __RemanFind $line 'all'
    if ($chosen) { __RemanPut $line $chosen }
    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
  }
  # Tab: normal completion first; with nothing to complete, the grey prediction if one is shown;
  # only when neither changes anything (empty line, or nothing matches) does the finder open,
  # seeded with what's typed. Shift+Tab keeps its default.
  function global:__RemanKeyTab {
    param($key, $arg)
    $line = $null; $cur = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
    # `reman ...`: a menu of choices with their descriptions, never the finder
    if ($line -match '^\s*reman(\.exe)?(\s|$)') {
      [Microsoft.PowerShell.PSConsoleReadLine]::MenuComplete($key, $arg)
      return
    }
    if (-not [string]::IsNullOrWhiteSpace($line)) {
      [Microsoft.PowerShell.PSConsoleReadLine]::TabCompleteNext($key, $arg)
      $after = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$after, [ref]$cur)
      if ($after -ne $line) { return }
      # nothing to complete: PowerShell's grey prediction, when one is showing (PSReadLine 2.1+)
      try { [Microsoft.PowerShell.PSConsoleReadLine]::AcceptSuggestion($key, $arg) } catch { }
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$after, [ref]$cur)
      if ($after -ne $line) { return }
    }
    $chosen = __RemanFind $line 'folder'
    if ($chosen) { __RemanPut $line $chosen }
    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
  }
  # Insert the fix (Alt+F). With no fix waiting it does what the key did before reman: Alt+F is
  # ForwardWord in Emacs mode (macOS and Linux), which also accepts one word of a prediction;
  # unbound in Windows mode, so nothing there.
  function global:__RemanKeyFix {
    param($key, $arg)
    if ($global:__RemanFix) {
      $line = $null; $cur = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $global:__RemanFix)
    } else {
      # nothing found before (Emacs mode set later in the profile, or a reload after an update,
      # when the binding was reman's own): Emacs mode's default for Alt+F
      $prev = __RemanPrevOf 'Fix'
      if (-not $prev -and "$((Get-PSReadLineOption).EditMode)" -eq 'Emacs' -and $key -and $key.Key -eq [ConsoleKey]::F -and $key.Modifiers -eq [ConsoleModifiers]::Alt) { $prev = 'ForwardWord' }
      if ($prev) { [Microsoft.PowerShell.PSConsoleReadLine]::($prev).Invoke($key, $arg) }
    }
  }
  # Alt+N on an empty prompt: what you'd run next here, ready to edit (Alt+N again: the next
  # idea, up to 3). With other text typed, what the key did before reman.
  function global:__RemanKeyNext {
    param($key, $arg)
    $line = $null; $cur = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
    $empty = $line.Trim() -eq ''
    if ($empty -or ($global:__RemanNext -and $line -eq $global:__RemanNext)) {
      $i = if ($empty) { 0 } else { $global:__RemanNextI + 1 }
      $r = $null
      try { $r = __RemanSend @{ op = 'nextup'; cwd = (Get-Location).Path; session = $env:REMAN_SESSION; index = $i } 400 $false 60 } catch { }
      if ($r -and $r.command) {
        $global:__RemanNext = [string]$r.command; $global:__RemanNextI = [int]$r.index
        if ($empty) {
          # why, once, above a fresh prompt (cycling just swaps the line)
          $e = [char]27
          $more = if ($r.of -gt 1) { "   ($global:__RemanNextKey again: $($r.of - 1) more)" } else { '' }
          [Console]::Write("$e[K`n$e[J$e[90m  reman: $($r.reason)$more$e[0m`n")
          [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt($null, [Console]::CursorTop)
        }
        [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $global:__RemanNext)
        return
      }
      if ($empty) { return }
    }
    __RemanPrev $key $arg 'Next' | Out-Null
  }
  # Enter: a command that keeps failing here is held once, with why (and the fix, on Alt+F);
  # Enter again runs it. An exact lookup with tight timeouts: a slow or absent daemon never
  # delays a command.
  function global:__RemanKeyHold {
    param($key, $arg)
    $line = $null; $cur = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
    $t = $line.Trim()
    $quiet = $global:__RemanQuietUntil -and [DateTime]::UtcNow -lt $global:__RemanQuietUntil
    if ($t.Length -gt 1 -and -not $quiet -and -not $line.StartsWith(' ') -and -not $line.Contains("`n") -and $t -ne $global:__RemanHeld) {
      $r = $null
      $sw = [Diagnostics.Stopwatch]::StartNew()
      try { $r = __RemanSend @{ op = 'precheck'; command = $t; cwd = (Get-Location).Path } 150 $false 60 } catch { }
      # no daemon to ask (the connect timed out): don't make every Enter wait for it, for a while
      if (-not $r -and $sw.ElapsedMilliseconds -ge 55) { $global:__RemanQuietUntil = [DateTime]::UtcNow.AddSeconds(30) }
      if ($r -and $r.warn) {
        $global:__RemanHeld = $t
        $e = [char]27
        $msg = "$e[K`n$e[J$e[33m  reman: $($r.warn)$e[0m"
        if ($r.error) { $msg += "`n$e[90m         last error: $($r.error)$e[0m" }
        if ($r.fix) {
          $global:__RemanFix = [string]$r.fix
          $how = if ($r.diff) { "$($r.diff); $global:__RemanFixHint" } else { $global:__RemanFixHint }
          $msg += "`n$e[90m  reman: worked instead -> $e[36m$($r.fix)$e[90m   ($how)$e[0m"
        }
        $msg += "`n$e[90m  Enter again runs it anyway$e[0m`n"
        [Microsoft.PowerShell.PSConsoleReadLine]::EndOfLine()
        [Console]::Write($msg)
        # a fresh prompt under the note, with the line as it was
        [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt($null, [Console]::CursorTop)
        return
      }
    }
    $global:__RemanHeld = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::AcceptLine($key, $arg)
  }

  # Bind reman's keys: [chord, action] pairs, from `reman settings` (Keys). Each key's previous
  # function is kept, to give the key back when reman lets go of it and for Alt+F / Alt+N to fall
  # back to; keys reman bound before (an older map, before a reload) are given back first.
  function global:__RemanBindKeys {
    param($pairs)
    if ($null -eq $global:__RemanPrevKey) { $global:__RemanPrevKey = @{} }
    # (the first time there are none: @($null) is one $null, not an empty list)
    foreach ($c in @($global:__RemanBoundKeys | Where-Object { $_ })) {
      $f = $global:__RemanPrevKey[$c]
      try { if ($f) { Set-PSReadLineKeyHandler -Chord $c -Function $f } else { Remove-PSReadLineKeyHandler -Chord $c } } catch { }
    }
    $global:__RemanBoundKeys = @()
    $global:__RemanPrevFor = @{}
    foreach ($p in $pairs) {
      $chord = $p[0]; $action = $p[1]
      if (-not $global:__RemanPrevKey.ContainsKey($chord)) {
        $h = Get-PSReadLineKeyHandler -Bound | Where-Object { $_.Key -ceq $chord } | Select-Object -First 1
        $f = ''
        try { if ($h -and [Microsoft.PowerShell.PSConsoleReadLine].GetMethod($h.Function)) { $f = $h.Function } } catch { }
        $global:__RemanPrevKey[$chord] = $f
      }
      if (-not $global:__RemanPrevFor.ContainsKey($action)) { $global:__RemanPrevFor[$action] = $global:__RemanPrevKey[$chord] }
      # which key ran it, so each one can fall back to what it did before
      $sb = [scriptblock]::Create("param(`$key, `$arg) `$global:__RemanChord = '$chord'; __RemanKey$action `$key `$arg")
      Set-PSReadLineKeyHandler -Chord $chord -BriefDescription "reman: $action" -ScriptBlock $sb
      $global:__RemanBoundKeys += $chord
    }
  }
  __KEYS__
}
