# reman shell integration for bash (generated by `reman init bash`).
# Capture is FORK-FREE: history is read via builtin redirection, JSON is built with parameter
# expansion, and the run goes straight to the daemon over bash's own /dev/tcp. Only when the
# daemon is down is the slim reman-hook spawned (it spools the run and starts the daemon).
#   Up = finder (this folder)   Ctrl-R = finder (all folders)   Alt-F = insert suggested fix
#   Tab on an empty line = finder (Tab after text is normal completion)
__reman_exe="__REMAN__"
__reman_hook="__HOOK__"
__reman_port=__PORT__
reman() { "$__reman_exe" "$@"; }
[ -z "$REMAN_SESSION" ] && export REMAN_SESSION="bash-$$-$RANDOM$RANDOM"
__reman_histfile="${TMPDIR:-/tmp}/.reman-hist-$$"
# a command typed with a leading space is never recorded
case ":$HISTCONTROL:" in *:ignorespace:*|*:ignoreboth:*) ;; *) HISTCONTROL="${HISTCONTROL:+$HISTCONTROL:}ignorespace" ;; esac

__reman_q() { # JSON-quote $1 into REPLY
  local s=$1
  s=${s//\\/\\\\}; s=${s//\"/\\\"}; s=${s//$'\n'/\\n}; s=${s//$'\r'/\\r}; s=${s//$'\t'/\\t}
  s=${s//[[:cntrl:]]/}
  REPLY="\"$s\""
}

__reman_ms() { local t=${EPOCHREALTIME/[.,]/}; REPLY=$(( 10#$t / 1000 )); }

__reman_preexec() {
  [ -n "$COMP_LINE" ] && return
  [ -n "$__reman_start" ] && return
  __reman_ms; __reman_start=$REPLY
}

__reman_precmd() {
  local ec=$? start=$__reman_start line num cmd
  __reman_start=
  [ -z "$start" ] && return $ec
  builtin history 1 > "$__reman_histfile" 2>/dev/null || return $ec
  IFS= read -r -d '' line < "$__reman_histfile"
  [[ $line =~ ^[[:space:]]*([0-9]+)\*?[[:space:]]+(.*)$ ]] || return $ec
  num=${BASH_REMATCH[1]}; cmd=${BASH_REMATCH[2]}; cmd=${cmd%$'\n'}
  [ "$num" = "$__reman_last_num" ] && return $ec
  __reman_last_num=$num
  [ -z "$cmd" ] && return $ec
  __reman_ms; local dur=$(( REPLY - start ))
  __reman_q "$cmd"; local qc=$REPLY
  __reman_q "$PWD"; local qd=$REPLY
  __reman_q "$REMAN_SESSION"; local qs=$REPLY
  local json="{\"op\":\"ingest\",\"command\":$qc,\"exit\":$ec,\"cwd\":$qd,\"session\":$qs,\"actor\":\"human\",\"duration_ms\":$dur,\"ts\":$EPOCHSECONDS}"
  local fd= reply=
  { exec {fd}<>"/dev/tcp/127.0.0.1/$__reman_port"; } 2>/dev/null
  if [ -n "$fd" ]; then
    printf '%s\n' "$json" >&$fd
    [ "$ec" -ne 0 ] && IFS= read -r -t 0.6 -u $fd reply
    exec {fd}>&-
  else
    ("$__reman_hook" record --exit "$ec" --cwd "$PWD" --duration-ms "$dur" -- "$cmd" &) >/dev/null 2>&1
  fi
  if [[ $reply =~ \"suggest\":\{\"command\":\"(([^\"\\]|\\.)*)\" ]]; then
    local fix=${BASH_REMATCH[1]} lead="did you mean"
    fix=${fix//\\\"/\"}; fix=${fix//\\\\/\\}
    [[ $reply == *'"kind":"proven"'* ]] && lead="last time this failed you ran"
    __reman_fix=$fix
    printf '\e[90m  reman: %s -> \e[36m%s\e[90m   (Alt-F inserts)\e[0m\n' "$lead" "$fix" >&2
  fi
  return $ec
}

trap '__reman_preexec' DEBUG
PROMPT_COMMAND="__reman_precmd${PROMPT_COMMAND:+; $PROMPT_COMMAND}"

__reman_find() {
  local scope=${1:-all} picked
  picked=$(REMAN_FIND_QUERY="$READLINE_LINE" "$__reman_exe" find --scope "$scope" --cwd "$PWD")
  if [ -n "$picked" ]; then
    READLINE_LINE="$picked"
    READLINE_POINT=${#READLINE_LINE}
  fi
}
__reman_insert_fix() {
  [ -n "$__reman_fix" ] || return
  READLINE_LINE="$__reman_fix"
  READLINE_POINT=${#READLINE_LINE}
}
# Tab on an EMPTY line opens the finder (readline's empty-line completion hook); Tab after text
# stays normal completion.
__reman_tab_empty() {
  local picked
  picked=$("$__reman_exe" find --scope folder --cwd "$PWD")
  COMPREPLY=()
  [ -n "$picked" ] && COMPREPLY=("$picked")
}
complete -o nospace -E -F __reman_tab_empty 2>/dev/null
bind -x '"\C-r": __reman_find all'
bind -x '"\e[A": __reman_find folder'
bind -x '"\ef": __reman_insert_fix'
