# reman shell integration for fish (generated by `reman init fish`).
set -g __reman_exe "__REMAN__"
function reman; $__reman_exe $argv; end
if not set -q REMAN_SESSION
    set -gx REMAN_SESSION (random)(random)-$fish_pid
end

function __reman_postexec --on-event fish_postexec
    set -l ec $status
    set -l cmd $argv[1]
    test -z "$cmd"; and return
    if test $ec -ne 0
        $__reman_exe record --exit $ec --cwd $PWD --duration-ms $CMD_DURATION --suggest -- $cmd
    else
        $__reman_exe record --exit $ec --cwd $PWD --duration-ms $CMD_DURATION -- $cmd &
        disown 2>/dev/null
    end
end

function __reman_find
    set -l scope $argv[1]
    set -l picked (env REMAN_FIND_QUERY=(commandline) $__reman_exe find --scope $scope --cwd $PWD)
    if test -n "$picked"
        commandline -r -- $picked
    end
    commandline -f repaint
end
bind \cr '__reman_find all'
bind \e\[A '__reman_find folder'
