# reman shell integration (generated by `reman init powershell`). Replaces Atuin: captures every
# command with cwd + real exit code + duration + session, and binds the native finder.
#   UpArrow = finder scoped to this folder   Ctrl+R = finder over all folders   Alt+F = insert fix
#   Tab = normal completion; when there's nothing to complete, the finder
$global:__RemanExe = "__REMAN__"
# `reman` is the exe on PATH, not a wrapper function: PowerShell only gives native commands
# their argument completer (below)
$__remanDir = Split-Path -Parent $global:__RemanExe
if (($env:PATH -split ';') -notcontains $__remanDir) { $env:PATH = "$__remanDir;$env:PATH" }
Remove-Item Function:\reman -ErrorAction SilentlyContinue

# Tab completion for reman itself - the same engine as bash / zsh / fish (`reman complete`):
# subcommands and flags with their help, agents with their status, folders you could share,
# your own commands for forget / pin / check / fixes.
Register-ArgumentCompleter -Native -CommandName 'reman', 'reman.exe' -ScriptBlock {
  param($wordToComplete, $commandAst, $cursorPosition)
  $text = $commandAst.ToString()
  $upto = [Math]::Min([Math]::Max($cursorPosition - $commandAst.Extent.StartOffset, 0), $text.Length)
  $before = $text.Substring(0, $upto)
  $head = $before.Substring(0, $before.Length - [Math]::Min($wordToComplete.Length, $before.Length))
  $enc = [Console]::OutputEncoding
  try {
    [Console]::OutputEncoding = [Text.Encoding]::UTF8
    $lines = & $global:__RemanExe complete "--line=$head" "--cur=$wordToComplete" 2>$null
  } finally { [Console]::OutputEncoding = $enc }
  foreach ($l in @($lines)) {
    if (-not $l) { continue }
    $v, $d = $l -split "`t", 2
    $insert = if ($v -match "[\s'`"``$;&|(){}@#,]") { "'" + ($v -replace "'", "''") + "'" } else { $v }
    $type = if ($v.StartsWith('-')) { 'ParameterName' } else { 'ParameterValue' }
    [System.Management.Automation.CompletionResult]::new($insert, $v, $type, $(if ($d) { $d } else { $v }))
  }
}
if (-not $env:REMAN_SESSION) { $env:REMAN_SESSION = [guid]::NewGuid().ToString() }

# One JSON line to the daemon. $waitMs > 0 waits (bounded) for the reply. If the daemon is down the
# run goes to the spool file (drained on next start) and the daemon is started in the background.
function global:__RemanSend {
  param($obj, [int]$waitMs = 0)
  $json = ($obj | ConvertTo-Json -Compress)
  try {
    $c = New-Object Net.Sockets.TcpClient
    $iar = $c.BeginConnect('127.0.0.1', __PORT__, $null, $null)
    if (-not $iar.AsyncWaitHandle.WaitOne(250)) { $c.Close(); throw 'reman daemon down' }
    $c.EndConnect($iar)
    $st = $c.GetStream()
    $b = [Text.Encoding]::UTF8.GetBytes($json + "`n")
    $st.Write($b, 0, $b.Length); $st.Flush()
    $resp = $null
    if ($waitMs -gt 0) {
      $st.ReadTimeout = $waitMs
      try { $resp = (New-Object IO.StreamReader($st, [Text.Encoding]::UTF8)).ReadLine() | ConvertFrom-Json } catch { }
    }
    $c.Close()
    return $resp
  } catch {
    try { [IO.File]::AppendAllText("__SPOOL__", $json + "`n", (New-Object Text.UTF8Encoding($false))) } catch { }
    $now = [DateTime]::UtcNow
    if (-not $global:__RemanSpawned -or ($now - $global:__RemanSpawned).TotalSeconds -gt 30) {
      $global:__RemanSpawned = $now
      try { Start-Process -FilePath $global:__RemanExe -ArgumentList 'daemon' -WindowStyle Hidden } catch { }
    }
    return $null
  }
}

# Warm the daemon when the shell starts (non-blocking), so the very first failure already gets a
# suggestion instead of landing in the spool.
try {
  $__c = New-Object Net.Sockets.TcpClient
  $__iar = $__c.BeginConnect('127.0.0.1', __PORT__, $null, $null)
  if (-not $__iar.AsyncWaitHandle.WaitOne(150)) {
    $global:__RemanSpawned = [DateTime]::UtcNow
    Start-Process -FilePath $global:__RemanExe -ArgumentList 'daemon' -WindowStyle Hidden
  }
  $__c.Close()
} catch { }

# Capture: wrap the prompt (guarded against double-wrap). Reads $? / $LASTEXITCODE FIRST, then
# restores $LASTEXITCODE so the original prompt's exit indicator still works. A command typed with
# a leading space is never recorded.
if (-not $global:__RemanPromptHooked) {
  $global:__RemanPromptHooked = $true
  $global:__RemanOrigPrompt = $function:prompt
  $global:__RemanLastHistId = -1
  function global:prompt {
    # `$?` MUST be read first: any statement before it (even an assignment) resets it to True,
    # which silently recorded every command as a success.
    $ok = $global:?
    $code = $global:LASTEXITCODE
    try {
      $h = Get-History -Count 1
      if ($h -and $h.Id -ne $global:__RemanLastHistId) {
        $global:__RemanLastHistId = $h.Id
        $cmd = $h.CommandLine
        if ($cmd -and -not $cmd.StartsWith(' ') -and $cmd.Trim().Length -gt 1) {
          $exit = if ($ok) { 0 } elseif ($code) { $code } else { 1 }
          $dur = [int64]($h.EndExecutionTime - $h.StartExecutionTime).TotalMilliseconds
          $req = @{ op = 'ingest'; command = $cmd; exit = $exit; cwd = (Get-Location).Path;
                    session = $env:REMAN_SESSION; actor = 'human'; duration_ms = $dur }
          if ($exit -ne 0) {
            $r = __RemanSend $req 400
            if ($r -and $r.suggest -and $r.suggest.command) {
              $global:__RemanFix = [string]$r.suggest.command
              $lead = if ($r.suggest.kind -eq 'proven') { 'last time this failed you ran' } else { 'did you mean' }
              Write-Host "  reman: $lead -> " -NoNewline -ForegroundColor DarkGray
              Write-Host $global:__RemanFix -NoNewline -ForegroundColor Cyan
              Write-Host '   (Alt+F inserts)' -ForegroundColor DarkGray
            }
          } else { [void](__RemanSend $req 0) }
        }
      }
    } catch { }
    $global:LASTEXITCODE = $code
    if ($global:__RemanOrigPrompt) { & $global:__RemanOrigPrompt } else { "PS " + (Get-Location).Path + "> " }
  }
}

# Native finder. The query travels via env (Windows PowerShell 5.1 drops empty native args and
# mangles embedded quotes); the pick comes back through a temp file.
function global:__RemanFind {
  param([string]$line, [string]$scope)
  $tmp = [IO.Path]::GetTempFileName()
  $env:REMAN_FIND_QUERY = $line
  try {
    & $global:__RemanExe find --scope $scope --cwd ((Get-Location).Path) --result-file $tmp
    $chosen = [IO.File]::ReadAllText($tmp, [Text.Encoding]::UTF8)
  } catch { $chosen = $null }
  finally { Remove-Item Env:\REMAN_FIND_QUERY -ErrorAction SilentlyContinue; Remove-Item $tmp -ErrorAction SilentlyContinue }
  if ($chosen) { return $chosen.TrimEnd("`r", "`n") }
  return $null
}

if (Get-Module PSReadLine -ErrorAction SilentlyContinue) {
  Set-PSReadLineKeyHandler -Chord 'UpArrow' -BriefDescription 'reman history finder (this folder)' -ScriptBlock {
    $line = $null; $cur = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
    if ($line.Contains("`n")) { [Microsoft.PowerShell.PSConsoleReadLine]::PreviousLine(); return }
    $chosen = __RemanFind $line 'folder'
    if ($chosen) { [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $chosen) }
    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
  }
  Set-PSReadLineKeyHandler -Chord 'Ctrl+r' -BriefDescription 'reman history finder (all folders)' -ScriptBlock {
    $line = $null; $cur = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
    $chosen = __RemanFind $line 'all'
    if ($chosen) { [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $chosen) }
    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
  }
  # Tab: normal completion first; only when it changes nothing (empty line, or nothing matches)
  # does the finder open, seeded with what's typed. Shift+Tab keeps its default.
  Set-PSReadLineKeyHandler -Chord 'Tab' -BriefDescription 'complete, else reman finder' -ScriptBlock {
    param($key, $arg)
    $line = $null; $cur = $null
    [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
    # `reman ...`: a menu of choices with their descriptions, never the finder
    if ($line -match '^\s*reman(\.exe)?(\s|$)') {
      [Microsoft.PowerShell.PSConsoleReadLine]::MenuComplete($key, $arg)
      return
    }
    if (-not [string]::IsNullOrWhiteSpace($line)) {
      [Microsoft.PowerShell.PSConsoleReadLine]::TabCompleteNext($key, $arg)
      $after = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$after, [ref]$cur)
      if ($after -ne $line) { return }
    }
    $chosen = __RemanFind $line 'folder'
    if ($chosen) { [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $chosen) }
    [Microsoft.PowerShell.PSConsoleReadLine]::InvokePrompt()
  }
  Set-PSReadLineKeyHandler -Chord 'Alt+f' -BriefDescription 'reman: insert suggested fix' -ScriptBlock {
    if ($global:__RemanFix) {
      $line = $null; $cur = $null
      [Microsoft.PowerShell.PSConsoleReadLine]::GetBufferState([ref]$line, [ref]$cur)
      [Microsoft.PowerShell.PSConsoleReadLine]::Replace(0, $line.Length, $global:__RemanFix)
    }
  }
}
