# reman shell integration for fish (generated by `reman init fish`).
# fish has no TCP builtin. Successes are appended to reman's spool file using builtins only
# (no process at all; the daemon drains it every second). A failure runs the slim reman-hook
# (no ONNX, ~2MB) and waits briefly for the fix suggestion.
#   Up = finder (this folder)   Ctrl-R = finder (all folders)   Alt-F = insert suggested fix
#   Tab on an empty line = finder (Tab after text is normal completion)
set -g __reman_exe "__REMAN__"
set -g __reman_hook "__HOOK__"
set -g __reman_spool "__SPOOL__"
# MSYS2/Cygwin fish can run C:/ paths but can't redirect into them: use the POSIX form
if string match -qr '^[A-Za-z]:' -- $__reman_spool; and command -q cygpath
    set __reman_spool (cygpath -u -- $__reman_spool)
end
function reman; $__reman_exe $argv; end
if not set -q REMAN_SESSION
    set -gx REMAN_SESSION fish-$fish_pid-(random)(random)
end

# warm the daemon once per shell (it drains the spool and answers the finder)
$__reman_exe ping >/dev/null 2>&1 &
disown 2>/dev/null

# JSON-quote $argv into $__reman_qv. One builtin pipeline, result in a global: calling a FUNCTION
# inside a command substitution costs ~50ms on MSYS fish, builtins ~1ms.
function __reman_q
    set -l s (string replace -a -- '\\' '\\\\' $argv | string replace -a -- '"' '\\"' | string replace -a -- \t '\\t' | string replace -a -- \r '\\r')
    set -g __reman_qv '"'(string join '\n' -- $s)'"'
end

function __reman_postexec --on-event fish_postexec
    set -l ec $status
    set -l cmd $argv[1]
    test -z "$cmd"; and return
    string match -q -- ' *' $cmd; and return   # leading space: never recorded
    if test $ec -ne 0
        set -g __reman_fix ($__reman_hook record --exit $ec --cwd $PWD --duration-ms $CMD_DURATION --suggest --print-fix -- $cmd)
    else
        __reman_q $cmd; set -l qc $__reman_qv
        __reman_q $PWD; set -l qd $__reman_qv
        __reman_q $REMAN_SESSION; set -l qs $__reman_qv
        echo '{"op":"ingest","command":'$qc',"exit":'$ec',"cwd":'$qd',"session":'$qs',"actor":"human","duration_ms":'$CMD_DURATION'}' >>$__reman_spool
    end
end

function __reman_find
    set -l scope $argv[1]
    set -l picked (env REMAN_FIND_QUERY=(commandline) $__reman_exe find --scope $scope --cwd $PWD)
    if test -n "$picked"
        commandline -r -- $picked
    end
    commandline -f repaint
end

function __reman_insert_fix
    test -n "$__reman_fix"; and commandline -r -- $__reman_fix
end

function __reman_tab
    if test -z (commandline)
        __reman_find folder
    else
        commandline -f complete
    end
end

bind \t __reman_tab

# Tab completion for reman itself (the same engine every shell uses: `reman complete`);
# fish reads `value<TAB>description` natively
function __reman_complete
    $__reman_exe complete "--line="(string join ' ' -- (commandline -opc))" " "--cur="(commandline -ct) 2>/dev/null
end
complete -c reman -f -a '(__reman_complete)'
complete -c reman.exe -f -a '(__reman_complete)'
bind \cr '__reman_find all'
bind \e\[A '__reman_find folder'
bind \ef __reman_insert_fix
