# reman shell integration for zsh (generated by `reman init zsh`).
# Capture spawns no process: preexec hands us the command line, zsh/datetime times it, and the
# run goes straight to the daemon over zsh/net/tcp. Only when the daemon is down is the slim
# reman-hook spawned (it spools the run and starts the daemon).
#   Up = finder (this folder)   Ctrl-R = finder (all folders)   Alt-F = insert suggested fix
#   Tab on an empty line = finder (Tab after text is normal completion)
__reman_exe="__REMAN__"
__reman_hook="__HOOK__"
__reman_port=__PORT__
reman() { "$__reman_exe" "$@" }
[[ -z "$REMAN_SESSION" ]] && export REMAN_SESSION="zsh-$$-$RANDOM$RANDOM"
zmodload zsh/datetime 2>/dev/null
zmodload zsh/net/tcp 2>/dev/null
autoload -Uz add-zsh-hook

__reman_q() { # JSON-quote $1 into REPLY
  local s=$1
  s=${s//\\/\\\\}; s=${s//\"/\\\"}; s=${s//$'\n'/\\n}; s=${s//$'\r'/\\r}; s=${s//$'\t'/\\t}
  s=${s//[[:cntrl:]]/}
  REPLY="\"$s\""
}

__reman_preexec() {
  __reman_cmd=$1
  __reman_start=$EPOCHREALTIME
}

__reman_precmd() {
  local ec=$?
  [[ -z $__reman_cmd ]] && return
  local cmd=$__reman_cmd
  __reman_cmd=
  [[ $cmd == ' '* ]] && return   # leading space: never recorded
  local -i dur   # integer var truncates; int() would need zsh/mathfunc
  (( dur = (EPOCHREALTIME - __reman_start) * 1000 ))
  __reman_q "$cmd"; local qc=$REPLY
  __reman_q "$PWD"; local qd=$REPLY
  __reman_q "$REMAN_SESSION"; local qs=$REPLY
  local json="{\"op\":\"ingest\",\"command\":$qc,\"exit\":$ec,\"cwd\":$qd,\"session\":$qs,\"actor\":\"human\",\"duration_ms\":$dur,\"ts\":$EPOCHSECONDS}"
  local reply= fd
  if (( $+builtins[ztcp] )) && ztcp 127.0.0.1 $__reman_port 2>/dev/null; then
    fd=$REPLY
    print -r -- "$json" >&$fd
    (( ec != 0 )) && read -t 0.6 -r -u $fd reply
    ztcp -c $fd
  else
    ( "$__reman_hook" record --exit $ec --cwd "$PWD" --duration-ms $dur -- "$cmd" & ) >/dev/null 2>&1
  fi
  if [[ $reply =~ '"suggest":\{"command":"(([^"\\]|\\.)*)"' ]]; then
    local fix=$match[1] lead="did you mean"
    fix=${fix//\\\"/\"}; fix=${fix//\\\\/\\}
    [[ $reply == *'"kind":"proven"'* ]] && lead="last time this failed you ran"
    __reman_fix=$fix
    print -P -- "%F{8}  reman: $lead -> %F{6}${fix//\%/%%}%F{8}   (Alt-F inserts)%f" >&2
  fi
}
add-zsh-hook preexec __reman_preexec
add-zsh-hook precmd __reman_precmd

__reman_find_widget() {
  local scope=$1 picked
  picked=$(REMAN_FIND_QUERY="$BUFFER" "$__reman_exe" find --scope "$scope" --cwd "$PWD" </dev/tty)
  if [[ -n "$picked" ]]; then
    BUFFER="$picked"
    CURSOR=${#BUFFER}
  fi
  zle reset-prompt
}
__reman_find_all() { __reman_find_widget all }
__reman_find_here() { __reman_find_widget folder }
__reman_insert_fix() {
  [[ -n $__reman_fix ]] || return
  BUFFER=$__reman_fix
  CURSOR=${#BUFFER}
}
# Tab on an empty line opens the finder; otherwise normal completion
__reman_tab() {
  if [[ -z $BUFFER ]]; then __reman_find_widget folder; else zle expand-or-complete; fi
}
zle -N __reman_tab
bindkey '^I' __reman_tab

# Tab completion for reman itself (the same engine every shell uses: `reman complete`)
_reman() {
  local -a descs
  local l v
  for l in "${(@f)$("$__reman_exe" complete "--line=${(j: :)words[1,CURRENT-1]} " "--cur=$PREFIX" 2>/dev/null)}"; do
    [[ -z $l ]] && continue
    v=${l%%$'\t'*}
    descs+=("${v//:/\\:}:${l#*$'\t'}")
  done
  (( ${#descs} )) && _describe -t reman 'reman' descs
}
(( $+functions[compdef] )) || { autoload -Uz compinit && compinit -u }
compdef _reman reman reman.exe
zle -N __reman_find_all
zle -N __reman_find_here
zle -N __reman_insert_fix
bindkey '^R' __reman_find_all
bindkey '^[[A' __reman_find_here
bindkey '^[OA' __reman_find_here
bindkey '^[f' __reman_insert_fix
